// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/thalamus.proto

package thalamusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                 // The user's input or implicit search string
	TokenBudget   int32                  `protobuf:"varint,2,opt,name=token_budget,json=tokenBudget,proto3" json:"token_budget,omitempty"` // Max tokens allowed for the returned context
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`                                   // Optional filters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_thalamus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thalamus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_thalamus_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetTokenBudget() int32 {
	if x != nil {
		return x.TokenBudget
	}
	return 0
}

func (x *QueryRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ContextPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FormattedMarkdown string                 `protobuf:"bytes,1,opt,name=formatted_markdown,json=formattedMarkdown,proto3" json:"formatted_markdown,omitempty"` // The dense, context-optimized string
	EstimatedTokens   int32                  `protobuf:"varint,2,opt,name=estimated_tokens,json=estimatedTokens,proto3" json:"estimated_tokens,omitempty"`
	Sources           []string               `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"` // IDs of the nodes used to generate the context
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContextPayload) Reset() {
	*x = ContextPayload{}
	mi := &file_proto_thalamus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextPayload) ProtoMessage() {}

func (x *ContextPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thalamus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextPayload.ProtoReflect.Descriptor instead.
func (*ContextPayload) Descriptor() ([]byte, []int) {
	return file_proto_thalamus_proto_rawDescGZIP(), []int{1}
}

func (x *ContextPayload) GetFormattedMarkdown() string {
	if x != nil {
		return x.FormattedMarkdown
	}
	return ""
}

func (x *ContextPayload) GetEstimatedTokens() int32 {
	if x != nil {
		return x.EstimatedTokens
	}
	return 0
}

func (x *ContextPayload) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

type ThoughtTrace struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Prompt         string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ChainOfThought string                 `protobuf:"bytes,3,opt,name=chain_of_thought,json=chainOfThought,proto3" json:"chain_of_thought,omitempty"` // The internal reasoning
	FinalResponse  string                 `protobuf:"bytes,4,opt,name=final_response,json=finalResponse,proto3" json:"final_response,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ThoughtTrace) Reset() {
	*x = ThoughtTrace{}
	mi := &file_proto_thalamus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThoughtTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThoughtTrace) ProtoMessage() {}

func (x *ThoughtTrace) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thalamus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThoughtTrace.ProtoReflect.Descriptor instead.
func (*ThoughtTrace) Descriptor() ([]byte, []int) {
	return file_proto_thalamus_proto_rawDescGZIP(), []int{2}
}

func (x *ThoughtTrace) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ThoughtTrace) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ThoughtTrace) GetChainOfThought() string {
	if x != nil {
		return x.ChainOfThought
	}
	return ""
}

func (x *ThoughtTrace) GetFinalResponse() string {
	if x != nil {
		return x.FinalResponse
	}
	return ""
}

func (x *ThoughtTrace) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ThoughtTrace) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // Returns the ID of the saved Signal node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditResponse) Reset() {
	*x = AuditResponse{}
	mi := &file_proto_thalamus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditResponse) ProtoMessage() {}

func (x *AuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thalamus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditResponse.ProtoReflect.Descriptor instead.
func (*AuditResponse) Descriptor() ([]byte, []int) {
	return file_proto_thalamus_proto_rawDescGZIP(), []int{3}
}

func (x *AuditResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuditResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_proto_thalamus_proto protoreflect.FileDescriptor

const file_proto_thalamus_proto_rawDesc = "" +
	"\n" +
	"\x14proto/thalamus.proto\x12\x12wisdom.thalamus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"[\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12!\n" +
	"\ftoken_budget\x18\x02 \x01(\x05R\vtokenBudget\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"\x84\x01\n" +
	"\x0eContextPayload\x12-\n" +
	"\x12formatted_markdown\x18\x01 \x01(\tR\x11formattedMarkdown\x12)\n" +
	"\x10estimated_tokens\x18\x02 \x01(\x05R\x0festimatedTokens\x12\x18\n" +
	"\asources\x18\x03 \x03(\tR\asources\"\x85\x02\n" +
	"\fThoughtTrace\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12(\n" +
	"\x10chain_of_thought\x18\x03 \x01(\tR\x0echainOfThought\x12%\n" +
	"\x0efinal_response\x18\x04 \x01(\tR\rfinalResponse\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"D\n" +
	"\rAuditResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId2\xb7\x01\n" +
	"\bThalamus\x12V\n" +
	"\x0eHydrateContext\x12 .wisdom.thalamus.v1.QueryRequest\x1a\".wisdom.thalamus.v1.ContextPayload\x12S\n" +
	"\fAuditThought\x12 .wisdom.thalamus.v1.ThoughtTrace\x1a!.wisdom.thalamus.v1.AuditResponseB5Z3github.com/google/wisdom/pkg/thalamus/v1;thalamusv1b\x06proto3"

var (
	file_proto_thalamus_proto_rawDescOnce sync.Once
	file_proto_thalamus_proto_rawDescData []byte
)

func file_proto_thalamus_proto_rawDescGZIP() []byte {
	file_proto_thalamus_proto_rawDescOnce.Do(func() {
		file_proto_thalamus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_thalamus_proto_rawDesc), len(file_proto_thalamus_proto_rawDesc)))
	})
	return file_proto_thalamus_proto_rawDescData
}

var file_proto_thalamus_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_thalamus_proto_goTypes = []any{
	(*QueryRequest)(nil),          // 0: wisdom.thalamus.v1.QueryRequest
	(*ContextPayload)(nil),        // 1: wisdom.thalamus.v1.ContextPayload
	(*ThoughtTrace)(nil),          // 2: wisdom.thalamus.v1.ThoughtTrace
	(*AuditResponse)(nil),         // 3: wisdom.thalamus.v1.AuditResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
}
var file_proto_thalamus_proto_depIdxs = []int32{
	4, // 0: wisdom.thalamus.v1.ThoughtTrace.timestamp:type_name -> google.protobuf.Timestamp
	5, // 1: wisdom.thalamus.v1.ThoughtTrace.metadata:type_name -> google.protobuf.Struct
	0, // 2: wisdom.thalamus.v1.Thalamus.HydrateContext:input_type -> wisdom.thalamus.v1.QueryRequest
	2, // 3: wisdom.thalamus.v1.Thalamus.AuditThought:input_type -> wisdom.thalamus.v1.ThoughtTrace
	1, // 4: wisdom.thalamus.v1.Thalamus.HydrateContext:output_type -> wisdom.thalamus.v1.ContextPayload
	3, // 5: wisdom.thalamus.v1.Thalamus.AuditThought:output_type -> wisdom.thalamus.v1.AuditResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_thalamus_proto_init() }
func file_proto_thalamus_proto_init() {
	if File_proto_thalamus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_thalamus_proto_rawDesc), len(file_proto_thalamus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_thalamus_proto_goTypes,
		DependencyIndexes: file_proto_thalamus_proto_depIdxs,
		MessageInfos:      file_proto_thalamus_proto_msgTypes,
	}.Build()
	File_proto_thalamus_proto = out.File
	file_proto_thalamus_proto_goTypes = nil
	file_proto_thalamus_proto_depIdxs = nil
}
