// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/thalamus.proto

package thalamusv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Thalamus_HydrateContext_FullMethodName = "/wisdom.thalamus.v1.Thalamus/HydrateContext"
	Thalamus_AuditThought_FullMethodName   = "/wisdom.thalamus.v1.Thalamus/AuditThought"
)

// ThalamusClient is the client API for Thalamus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThalamusClient interface {
	// HydrateContext retrieves data from Cortex and formats it deterministically
	HydrateContext(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ContextPayload, error)
	// AuditThought asynchronously saves the LLM reasoning traces
	AuditThought(ctx context.Context, in *ThoughtTrace, opts ...grpc.CallOption) (*AuditResponse, error)
}

type thalamusClient struct {
	cc grpc.ClientConnInterface
}

func NewThalamusClient(cc grpc.ClientConnInterface) ThalamusClient {
	return &thalamusClient{cc}
}

func (c *thalamusClient) HydrateContext(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ContextPayload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextPayload)
	err := c.cc.Invoke(ctx, Thalamus_HydrateContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thalamusClient) AuditThought(ctx context.Context, in *ThoughtTrace, opts ...grpc.CallOption) (*AuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditResponse)
	err := c.cc.Invoke(ctx, Thalamus_AuditThought_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThalamusServer is the server API for Thalamus service.
// All implementations must embed UnimplementedThalamusServer
// for forward compatibility.
type ThalamusServer interface {
	// HydrateContext retrieves data from Cortex and formats it deterministically
	HydrateContext(context.Context, *QueryRequest) (*ContextPayload, error)
	// AuditThought asynchronously saves the LLM reasoning traces
	AuditThought(context.Context, *ThoughtTrace) (*AuditResponse, error)
	mustEmbedUnimplementedThalamusServer()
}

// UnimplementedThalamusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThalamusServer struct{}

func (UnimplementedThalamusServer) HydrateContext(context.Context, *QueryRequest) (*ContextPayload, error) {
	return nil, status.Error(codes.Unimplemented, "method HydrateContext not implemented")
}
func (UnimplementedThalamusServer) AuditThought(context.Context, *ThoughtTrace) (*AuditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuditThought not implemented")
}
func (UnimplementedThalamusServer) mustEmbedUnimplementedThalamusServer() {}
func (UnimplementedThalamusServer) testEmbeddedByValue()                  {}

// UnsafeThalamusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThalamusServer will
// result in compilation errors.
type UnsafeThalamusServer interface {
	mustEmbedUnimplementedThalamusServer()
}

func RegisterThalamusServer(s grpc.ServiceRegistrar, srv ThalamusServer) {
	// If the following call panics, it indicates UnimplementedThalamusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Thalamus_ServiceDesc, srv)
}

func _Thalamus_HydrateContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThalamusServer).HydrateContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Thalamus_HydrateContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThalamusServer).HydrateContext(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Thalamus_AuditThought_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThoughtTrace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThalamusServer).AuditThought(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Thalamus_AuditThought_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThalamusServer).AuditThought(ctx, req.(*ThoughtTrace))
	}
	return interceptor(ctx, in, info, handler)
}

// Thalamus_ServiceDesc is the grpc.ServiceDesc for Thalamus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Thalamus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wisdom.thalamus.v1.Thalamus",
	HandlerType: (*ThalamusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HydrateContext",
			Handler:    _Thalamus_HydrateContext_Handler,
		},
		{
			MethodName: "AuditThought",
			Handler:    _Thalamus_AuditThought_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/thalamus.proto",
}
