// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/cortex.proto

package cortexv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SemanticSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	DomainFilter  string                 `protobuf:"bytes,3,opt,name=domain_filter,json=domainFilter,proto3" json:"domain_filter,omitempty"`
	TypeFilter    string                 `protobuf:"bytes,4,opt,name=type_filter,json=typeFilter,proto3" json:"type_filter,omitempty"`
	MinScore      float64                `protobuf:"fixed64,5,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchRequest) Reset() {
	*x = SemanticSearchRequest{}
	mi := &file_proto_cortex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchRequest) ProtoMessage() {}

func (x *SemanticSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cortex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchRequest.ProtoReflect.Descriptor instead.
func (*SemanticSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_cortex_proto_rawDescGZIP(), []int{0}
}

func (x *SemanticSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SemanticSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SemanticSearchRequest) GetDomainFilter() string {
	if x != nil {
		return x.DomainFilter
	}
	return ""
}

func (x *SemanticSearchRequest) GetTypeFilter() string {
	if x != nil {
		return x.TypeFilter
	}
	return ""
}

func (x *SemanticSearchRequest) GetMinScore() float64 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_cortex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cortex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_cortex_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResult) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type SemanticSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchResponse) Reset() {
	*x = SemanticSearchResponse{}
	mi := &file_proto_cortex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchResponse) ProtoMessage() {}

func (x *SemanticSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cortex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchResponse.ProtoReflect.Descriptor instead.
func (*SemanticSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_cortex_proto_rawDescGZIP(), []int{2}
}

func (x *SemanticSearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SemanticSearchResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // Optional, if empty server generates one
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // Fact, Signal, Concept, User
	Payload       *structpb.Struct       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	RequiresHuman bool                   `protobuf:"varint,5,opt,name=requires_human,json=requiresHuman,proto3" json:"requires_human,omitempty"`
	Ttl           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_proto_cortex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cortex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_proto_cortex_proto_rawDescGZIP(), []int{3}
}

func (x *IngestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IngestRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IngestRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IngestRequest) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *IngestRequest) GetRequiresHuman() bool {
	if x != nil {
		return x.RequiresHuman
	}
	return false
}

func (x *IngestRequest) GetTtl() *timestamppb.Timestamp {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type NodeID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeID) Reset() {
	*x = NodeID{}
	mi := &file_proto_cortex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeID) ProtoMessage() {}

func (x *NodeID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cortex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeID.ProtoReflect.Descriptor instead.
func (*NodeID) Descriptor() ([]byte, []int) {
	return file_proto_cortex_proto_rawDescGZIP(), []int{4}
}

func (x *NodeID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RecallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"` // Default 1 (direct neighbors)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallRequest) Reset() {
	*x = RecallRequest{}
	mi := &file_proto_cortex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallRequest) ProtoMessage() {}

func (x *RecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cortex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallRequest.ProtoReflect.Descriptor instead.
func (*RecallRequest) Descriptor() ([]byte, []int) {
	return file_proto_cortex_proto_rawDescGZIP(), []int{5}
}

func (x *RecallRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecallRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	RequiresHuman bool                   `protobuf:"varint,5,opt,name=requires_human,json=requiresHuman,proto3" json:"requires_human,omitempty"`
	Ttl           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_proto_cortex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cortex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_cortex_proto_rawDescGZIP(), []int{6}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Node) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Node) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Node) GetRequiresHuman() bool {
	if x != nil {
		return x.RequiresHuman
	}
	return false
}

func (x *Node) GetTtl() *timestamppb.Timestamp {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *Node) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Node) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_proto_cortex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cortex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_proto_cortex_proto_rawDescGZIP(), []int{7}
}

func (x *Edge) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Edge) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Edge) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *Edge) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CognitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Center        *Node                  `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	OutEdges      []*Edge                `protobuf:"bytes,2,rep,name=out_edges,json=outEdges,proto3" json:"out_edges,omitempty"`
	InEdges       []*Edge                `protobuf:"bytes,3,rep,name=in_edges,json=inEdges,proto3" json:"in_edges,omitempty"`
	Neighbors     []*Node                `protobuf:"bytes,4,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CognitionResponse) Reset() {
	*x = CognitionResponse{}
	mi := &file_proto_cortex_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CognitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CognitionResponse) ProtoMessage() {}

func (x *CognitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cortex_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CognitionResponse.ProtoReflect.Descriptor instead.
func (*CognitionResponse) Descriptor() ([]byte, []int) {
	return file_proto_cortex_proto_rawDescGZIP(), []int{8}
}

func (x *CognitionResponse) GetCenter() *Node {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *CognitionResponse) GetOutEdges() []*Edge {
	if x != nil {
		return x.OutEdges
	}
	return nil
}

func (x *CognitionResponse) GetInEdges() []*Edge {
	if x != nil {
		return x.InEdges
	}
	return nil
}

func (x *CognitionResponse) GetNeighbors() []*Node {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

type FactRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // Search term or metadata filter
	MetadataFilters map[string]string      `protobuf:"bytes,2,rep,name=metadata_filters,json=metadataFilters,proto3" json:"metadata_filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FactRequest) Reset() {
	*x = FactRequest{}
	mi := &file_proto_cortex_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactRequest) ProtoMessage() {}

func (x *FactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cortex_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactRequest.ProtoReflect.Descriptor instead.
func (*FactRequest) Descriptor() ([]byte, []int) {
	return file_proto_cortex_proto_rawDescGZIP(), []int{9}
}

func (x *FactRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *FactRequest) GetMetadataFilters() map[string]string {
	if x != nil {
		return x.MetadataFilters
	}
	return nil
}

type FactList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facts         []*Node                `protobuf:"bytes,1,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactList) Reset() {
	*x = FactList{}
	mi := &file_proto_cortex_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactList) ProtoMessage() {}

func (x *FactList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cortex_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactList.ProtoReflect.Descriptor instead.
func (*FactList) Descriptor() ([]byte, []int) {
	return file_proto_cortex_proto_rawDescGZIP(), []int{10}
}

func (x *FactList) GetFacts() []*Node {
	if x != nil {
		return x.Facts
	}
	return nil
}

var File_proto_cortex_proto protoreflect.FileDescriptor

const file_proto_cortex_proto_rawDesc = "" +
	"\n" +
	"\x12proto/cortex.proto\x12\x10wisdom.cortex.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa6\x01\n" +
	"\x15SemanticSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12#\n" +
	"\rdomain_filter\x18\x03 \x01(\tR\fdomainFilter\x12\x1f\n" +
	"\vtype_filter\x18\x04 \x01(\tR\n" +
	"typeFilter\x12\x1b\n" +
	"\tmin_score\x18\x05 \x01(\x01R\bminScore\"d\n" +
	"\fSearchResult\x12*\n" +
	"\x04node\x18\x01 \x01(\v2\x16.wisdom.cortex.v1.NodeR\x04node\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"f\n" +
	"\x16SemanticSearchResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.wisdom.cortex.v1.SearchResultR\aresults\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"\xdb\x01\n" +
	"\rIngestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12%\n" +
	"\x0erequires_human\x18\x05 \x01(\bR\rrequiresHuman\x12,\n" +
	"\x03ttl\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x03ttl\"\x18\n" +
	"\x06NodeID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\rRecallRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"\xc8\x02\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12%\n" +
	"\x0erequires_human\x18\x05 \x01(\bR\rrequiresHuman\x12,\n" +
	"\x03ttl\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x03ttl\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x97\x01\n" +
	"\x04Edge\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xe1\x01\n" +
	"\x11CognitionResponse\x12.\n" +
	"\x06center\x18\x01 \x01(\v2\x16.wisdom.cortex.v1.NodeR\x06center\x123\n" +
	"\tout_edges\x18\x02 \x03(\v2\x16.wisdom.cortex.v1.EdgeR\boutEdges\x121\n" +
	"\bin_edges\x18\x03 \x03(\v2\x16.wisdom.cortex.v1.EdgeR\ainEdges\x124\n" +
	"\tneighbors\x18\x04 \x03(\v2\x16.wisdom.cortex.v1.NodeR\tneighbors\"\xc6\x01\n" +
	"\vFactRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12]\n" +
	"\x10metadata_filters\x18\x02 \x03(\v22.wisdom.cortex.v1.FactRequest.MetadataFiltersEntryR\x0fmetadataFilters\x1aB\n" +
	"\x14MetadataFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\bFactList\x12,\n" +
	"\x05facts\x18\x01 \x03(\v2\x16.wisdom.cortex.v1.NodeR\x05facts2\xcd\x02\n" +
	"\x06Cortex\x12E\n" +
	"\bMemorize\x12\x1f.wisdom.cortex.v1.IngestRequest\x1a\x18.wisdom.cortex.v1.NodeID\x12N\n" +
	"\x06Recall\x12\x1f.wisdom.cortex.v1.RecallRequest\x1a#.wisdom.cortex.v1.CognitionResponse\x12G\n" +
	"\n" +
	"QueryFacts\x12\x1d.wisdom.cortex.v1.FactRequest\x1a\x1a.wisdom.cortex.v1.FactList\x12c\n" +
	"\x0eSemanticSearch\x12'.wisdom.cortex.v1.SemanticSearchRequest\x1a(.wisdom.cortex.v1.SemanticSearchResponseB1Z/github.com/google/wisdom/pkg/cortex/v1;cortexv1b\x06proto3"

var (
	file_proto_cortex_proto_rawDescOnce sync.Once
	file_proto_cortex_proto_rawDescData []byte
)

func file_proto_cortex_proto_rawDescGZIP() []byte {
	file_proto_cortex_proto_rawDescOnce.Do(func() {
		file_proto_cortex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cortex_proto_rawDesc), len(file_proto_cortex_proto_rawDesc)))
	})
	return file_proto_cortex_proto_rawDescData
}

var file_proto_cortex_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_cortex_proto_goTypes = []any{
	(*SemanticSearchRequest)(nil),  // 0: wisdom.cortex.v1.SemanticSearchRequest
	(*SearchResult)(nil),           // 1: wisdom.cortex.v1.SearchResult
	(*SemanticSearchResponse)(nil), // 2: wisdom.cortex.v1.SemanticSearchResponse
	(*IngestRequest)(nil),          // 3: wisdom.cortex.v1.IngestRequest
	(*NodeID)(nil),                 // 4: wisdom.cortex.v1.NodeID
	(*RecallRequest)(nil),          // 5: wisdom.cortex.v1.RecallRequest
	(*Node)(nil),                   // 6: wisdom.cortex.v1.Node
	(*Edge)(nil),                   // 7: wisdom.cortex.v1.Edge
	(*CognitionResponse)(nil),      // 8: wisdom.cortex.v1.CognitionResponse
	(*FactRequest)(nil),            // 9: wisdom.cortex.v1.FactRequest
	(*FactList)(nil),               // 10: wisdom.cortex.v1.FactList
	nil,                            // 11: wisdom.cortex.v1.FactRequest.MetadataFiltersEntry
	(*structpb.Struct)(nil),        // 12: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),  // 13: google.protobuf.Timestamp
}
var file_proto_cortex_proto_depIdxs = []int32{
	6,  // 0: wisdom.cortex.v1.SearchResult.node:type_name -> wisdom.cortex.v1.Node
	1,  // 1: wisdom.cortex.v1.SemanticSearchResponse.results:type_name -> wisdom.cortex.v1.SearchResult
	12, // 2: wisdom.cortex.v1.IngestRequest.payload:type_name -> google.protobuf.Struct
	13, // 3: wisdom.cortex.v1.IngestRequest.ttl:type_name -> google.protobuf.Timestamp
	12, // 4: wisdom.cortex.v1.Node.payload:type_name -> google.protobuf.Struct
	13, // 5: wisdom.cortex.v1.Node.ttl:type_name -> google.protobuf.Timestamp
	13, // 6: wisdom.cortex.v1.Node.created_at:type_name -> google.protobuf.Timestamp
	13, // 7: wisdom.cortex.v1.Node.updated_at:type_name -> google.protobuf.Timestamp
	13, // 8: wisdom.cortex.v1.Edge.created_at:type_name -> google.protobuf.Timestamp
	6,  // 9: wisdom.cortex.v1.CognitionResponse.center:type_name -> wisdom.cortex.v1.Node
	7,  // 10: wisdom.cortex.v1.CognitionResponse.out_edges:type_name -> wisdom.cortex.v1.Edge
	7,  // 11: wisdom.cortex.v1.CognitionResponse.in_edges:type_name -> wisdom.cortex.v1.Edge
	6,  // 12: wisdom.cortex.v1.CognitionResponse.neighbors:type_name -> wisdom.cortex.v1.Node
	11, // 13: wisdom.cortex.v1.FactRequest.metadata_filters:type_name -> wisdom.cortex.v1.FactRequest.MetadataFiltersEntry
	6,  // 14: wisdom.cortex.v1.FactList.facts:type_name -> wisdom.cortex.v1.Node
	3,  // 15: wisdom.cortex.v1.Cortex.Memorize:input_type -> wisdom.cortex.v1.IngestRequest
	5,  // 16: wisdom.cortex.v1.Cortex.Recall:input_type -> wisdom.cortex.v1.RecallRequest
	9,  // 17: wisdom.cortex.v1.Cortex.QueryFacts:input_type -> wisdom.cortex.v1.FactRequest
	0,  // 18: wisdom.cortex.v1.Cortex.SemanticSearch:input_type -> wisdom.cortex.v1.SemanticSearchRequest
	4,  // 19: wisdom.cortex.v1.Cortex.Memorize:output_type -> wisdom.cortex.v1.NodeID
	8,  // 20: wisdom.cortex.v1.Cortex.Recall:output_type -> wisdom.cortex.v1.CognitionResponse
	10, // 21: wisdom.cortex.v1.Cortex.QueryFacts:output_type -> wisdom.cortex.v1.FactList
	2,  // 22: wisdom.cortex.v1.Cortex.SemanticSearch:output_type -> wisdom.cortex.v1.SemanticSearchResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_cortex_proto_init() }
func file_proto_cortex_proto_init() {
	if File_proto_cortex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cortex_proto_rawDesc), len(file_proto_cortex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cortex_proto_goTypes,
		DependencyIndexes: file_proto_cortex_proto_depIdxs,
		MessageInfos:      file_proto_cortex_proto_msgTypes,
	}.Build()
	File_proto_cortex_proto = out.File
	file_proto_cortex_proto_goTypes = nil
	file_proto_cortex_proto_depIdxs = nil
}
