// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/cortex.proto

package cortexv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Cortex_Memorize_FullMethodName       = "/wisdom.cortex.v1.Cortex/Memorize"
	Cortex_Recall_FullMethodName         = "/wisdom.cortex.v1.Cortex/Recall"
	Cortex_QueryFacts_FullMethodName     = "/wisdom.cortex.v1.Cortex/QueryFacts"
	Cortex_SemanticSearch_FullMethodName = "/wisdom.cortex.v1.Cortex/SemanticSearch"
)

// CortexClient is the client API for Cortex service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CortexClient interface {
	Memorize(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*NodeID, error)
	Recall(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*CognitionResponse, error)
	QueryFacts(ctx context.Context, in *FactRequest, opts ...grpc.CallOption) (*FactList, error)
	SemanticSearch(ctx context.Context, in *SemanticSearchRequest, opts ...grpc.CallOption) (*SemanticSearchResponse, error)
}

type cortexClient struct {
	cc grpc.ClientConnInterface
}

func NewCortexClient(cc grpc.ClientConnInterface) CortexClient {
	return &cortexClient{cc}
}

func (c *cortexClient) Memorize(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*NodeID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeID)
	err := c.cc.Invoke(ctx, Cortex_Memorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexClient) Recall(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*CognitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CognitionResponse)
	err := c.cc.Invoke(ctx, Cortex_Recall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexClient) QueryFacts(ctx context.Context, in *FactRequest, opts ...grpc.CallOption) (*FactList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FactList)
	err := c.cc.Invoke(ctx, Cortex_QueryFacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexClient) SemanticSearch(ctx context.Context, in *SemanticSearchRequest, opts ...grpc.CallOption) (*SemanticSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SemanticSearchResponse)
	err := c.cc.Invoke(ctx, Cortex_SemanticSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CortexServer is the server API for Cortex service.
// All implementations must embed UnimplementedCortexServer
// for forward compatibility.
type CortexServer interface {
	Memorize(context.Context, *IngestRequest) (*NodeID, error)
	Recall(context.Context, *RecallRequest) (*CognitionResponse, error)
	QueryFacts(context.Context, *FactRequest) (*FactList, error)
	SemanticSearch(context.Context, *SemanticSearchRequest) (*SemanticSearchResponse, error)
	mustEmbedUnimplementedCortexServer()
}

// UnimplementedCortexServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCortexServer struct{}

func (UnimplementedCortexServer) Memorize(context.Context, *IngestRequest) (*NodeID, error) {
	return nil, status.Error(codes.Unimplemented, "method Memorize not implemented")
}
func (UnimplementedCortexServer) Recall(context.Context, *RecallRequest) (*CognitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Recall not implemented")
}
func (UnimplementedCortexServer) QueryFacts(context.Context, *FactRequest) (*FactList, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryFacts not implemented")
}
func (UnimplementedCortexServer) SemanticSearch(context.Context, *SemanticSearchRequest) (*SemanticSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SemanticSearch not implemented")
}
func (UnimplementedCortexServer) mustEmbedUnimplementedCortexServer() {}
func (UnimplementedCortexServer) testEmbeddedByValue()                {}

// UnsafeCortexServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CortexServer will
// result in compilation errors.
type UnsafeCortexServer interface {
	mustEmbedUnimplementedCortexServer()
}

func RegisterCortexServer(s grpc.ServiceRegistrar, srv CortexServer) {
	// If the following call panics, it indicates UnimplementedCortexServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Cortex_ServiceDesc, srv)
}

func _Cortex_Memorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServer).Memorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cortex_Memorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServer).Memorize(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cortex_Recall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServer).Recall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cortex_Recall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServer).Recall(ctx, req.(*RecallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cortex_QueryFacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServer).QueryFacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cortex_QueryFacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServer).QueryFacts(ctx, req.(*FactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cortex_SemanticSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemanticSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexServer).SemanticSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cortex_SemanticSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexServer).SemanticSearch(ctx, req.(*SemanticSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cortex_ServiceDesc is the grpc.ServiceDesc for Cortex service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cortex_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wisdom.cortex.v1.Cortex",
	HandlerType: (*CortexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Memorize",
			Handler:    _Cortex_Memorize_Handler,
		},
		{
			MethodName: "Recall",
			Handler:    _Cortex_Recall_Handler,
		},
		{
			MethodName: "QueryFacts",
			Handler:    _Cortex_QueryFacts_Handler,
		},
		{
			MethodName: "SemanticSearch",
			Handler:    _Cortex_SemanticSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cortex.proto",
}
