// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/curriculum.proto

package curriculumv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`                                 // e.g., "React Server Components"
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`                               // "technology", "chess", "finance", "language"
	TargetLevel   int32                  `protobuf:"varint,3,opt,name=target_level,json=targetLevel,proto3" json:"target_level,omitempty"` // 1: Beginner, 5: Expert
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                 // Used to filter out already mastered concepts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathRequest) Reset() {
	*x = PathRequest{}
	mi := &file_proto_curriculum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRequest) ProtoMessage() {}

func (x *PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_curriculum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRequest.ProtoReflect.Descriptor instead.
func (*PathRequest) Descriptor() ([]byte, []int) {
	return file_proto_curriculum_proto_rawDescGZIP(), []int{0}
}

func (x *PathRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PathRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *PathRequest) GetTargetLevel() int32 {
	if x != nil {
		return x.TargetLevel
	}
	return 0
}

func (x *PathRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Module struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty      int32                  `protobuf:"varint,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`                                 // 1-5
	PrerequisiteIds []string               `protobuf:"bytes,5,rep,name=prerequisite_ids,json=prerequisiteIds,proto3" json:"prerequisite_ids,omitempty"` // IDs of modules that must come first
	ConceptNodeIds  []string               `protobuf:"bytes,6,rep,name=concept_node_ids,json=conceptNodeIds,proto3" json:"concept_node_ids,omitempty"`  // Cortex node IDs for atomic concepts
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_proto_curriculum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_proto_curriculum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_proto_curriculum_proto_rawDescGZIP(), []int{1}
}

func (x *Module) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Module) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Module) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Module) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *Module) GetPrerequisiteIds() []string {
	if x != nil {
		return x.PrerequisiteIds
	}
	return nil
}

func (x *Module) GetConceptNodeIds() []string {
	if x != nil {
		return x.ConceptNodeIds
	}
	return nil
}

type LearningPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       string                 `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	TopicTitle    string                 `protobuf:"bytes,2,opt,name=topic_title,json=topicTitle,proto3" json:"topic_title,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Modules       []*Module              `protobuf:"bytes,4,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearningPath) Reset() {
	*x = LearningPath{}
	mi := &file_proto_curriculum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearningPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearningPath) ProtoMessage() {}

func (x *LearningPath) ProtoReflect() protoreflect.Message {
	mi := &file_proto_curriculum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearningPath.ProtoReflect.Descriptor instead.
func (*LearningPath) Descriptor() ([]byte, []int) {
	return file_proto_curriculum_proto_rawDescGZIP(), []int{2}
}

func (x *LearningPath) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *LearningPath) GetTopicTitle() string {
	if x != nil {
		return x.TopicTitle
	}
	return ""
}

func (x *LearningPath) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *LearningPath) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

type NodeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIds       []string               `protobuf:"bytes,1,rep,name=node_ids,json=nodeIds,proto3" json:"node_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeList) Reset() {
	*x = NodeList{}
	mi := &file_proto_curriculum_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeList) ProtoMessage() {}

func (x *NodeList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_curriculum_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeList.ProtoReflect.Descriptor instead.
func (*NodeList) Descriptor() ([]byte, []int) {
	return file_proto_curriculum_proto_rawDescGZIP(), []int{3}
}

func (x *NodeList) GetNodeIds() []string {
	if x != nil {
		return x.NodeIds
	}
	return nil
}

type Dependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNodeId    string                 `protobuf:"bytes,1,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"` // Prerequisite
	ToNodeId      string                 `protobuf:"bytes,2,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`       // Dependent concept
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`                         // "PREREQUISITE_OF", "PART_OF", "EXTENDS"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	mi := &file_proto_curriculum_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_curriculum_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_proto_curriculum_proto_rawDescGZIP(), []int{4}
}

func (x *Dependency) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *Dependency) GetToNodeId() string {
	if x != nil {
		return x.ToNodeId
	}
	return ""
}

func (x *Dependency) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

type DependencyGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*Dependency          `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyGraph) Reset() {
	*x = DependencyGraph{}
	mi := &file_proto_curriculum_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyGraph) ProtoMessage() {}

func (x *DependencyGraph) ProtoReflect() protoreflect.Message {
	mi := &file_proto_curriculum_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyGraph.ProtoReflect.Descriptor instead.
func (*DependencyGraph) Descriptor() ([]byte, []int) {
	return file_proto_curriculum_proto_rawDescGZIP(), []int{5}
}

func (x *DependencyGraph) GetEdges() []*Dependency {
	if x != nil {
		return x.Edges
	}
	return nil
}

type DifficultyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // Raw content to analyze
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DifficultyRequest) Reset() {
	*x = DifficultyRequest{}
	mi := &file_proto_curriculum_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifficultyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifficultyRequest) ProtoMessage() {}

func (x *DifficultyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_curriculum_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifficultyRequest.ProtoReflect.Descriptor instead.
func (*DifficultyRequest) Descriptor() ([]byte, []int) {
	return file_proto_curriculum_proto_rawDescGZIP(), []int{6}
}

func (x *DifficultyRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DifficultyRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DifficultyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Tier          int32                  `protobuf:"varint,2,opt,name=tier,proto3" json:"tier,omitempty"` // 1-5
	Rationale     string                 `protobuf:"bytes,3,opt,name=rationale,proto3" json:"rationale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DifficultyResult) Reset() {
	*x = DifficultyResult{}
	mi := &file_proto_curriculum_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifficultyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifficultyResult) ProtoMessage() {}

func (x *DifficultyResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_curriculum_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifficultyResult.ProtoReflect.Descriptor instead.
func (*DifficultyResult) Descriptor() ([]byte, []int) {
	return file_proto_curriculum_proto_rawDescGZIP(), []int{7}
}

func (x *DifficultyResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DifficultyResult) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *DifficultyResult) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

type ReprioritizeRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StruggleNodeIds []string               `protobuf:"bytes,2,rep,name=struggle_node_ids,json=struggleNodeIds,proto3" json:"struggle_node_ids,omitempty"` // Concepts flagged as FRAGILE by Trace
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReprioritizeRequest) Reset() {
	*x = ReprioritizeRequest{}
	mi := &file_proto_curriculum_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReprioritizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReprioritizeRequest) ProtoMessage() {}

func (x *ReprioritizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_curriculum_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReprioritizeRequest.ProtoReflect.Descriptor instead.
func (*ReprioritizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_curriculum_proto_rawDescGZIP(), []int{8}
}

func (x *ReprioritizeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReprioritizeRequest) GetStruggleNodeIds() []string {
	if x != nil {
		return x.StruggleNodeIds
	}
	return nil
}

var File_proto_curriculum_proto protoreflect.FileDescriptor

const file_proto_curriculum_proto_rawDesc = "" +
	"\n" +
	"\x16proto/curriculum.proto\x12\x14wisdom.curriculum.v1\"w\n" +
	"\vPathRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12!\n" +
	"\ftarget_level\x18\x03 \x01(\x05R\vtargetLevel\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\xc5\x01\n" +
	"\x06Module\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\x05R\n" +
	"difficulty\x12)\n" +
	"\x10prerequisite_ids\x18\x05 \x03(\tR\x0fprerequisiteIds\x12(\n" +
	"\x10concept_node_ids\x18\x06 \x03(\tR\x0econceptNodeIds\"\x9a\x01\n" +
	"\fLearningPath\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\tR\atopicId\x12\x1f\n" +
	"\vtopic_title\x18\x02 \x01(\tR\n" +
	"topicTitle\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x126\n" +
	"\amodules\x18\x04 \x03(\v2\x1c.wisdom.curriculum.v1.ModuleR\amodules\"%\n" +
	"\bNodeList\x12\x19\n" +
	"\bnode_ids\x18\x01 \x03(\tR\anodeIds\"h\n" +
	"\n" +
	"Dependency\x12 \n" +
	"\ffrom_node_id\x18\x01 \x01(\tR\n" +
	"fromNodeId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x02 \x01(\tR\btoNodeId\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\"I\n" +
	"\x0fDependencyGraph\x126\n" +
	"\x05edges\x18\x01 \x03(\v2 .wisdom.curriculum.v1.DependencyR\x05edges\"F\n" +
	"\x11DifficultyRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"]\n" +
	"\x10DifficultyResult\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\x05R\x04tier\x12\x1c\n" +
	"\trationale\x18\x03 \x01(\tR\trationale\"Z\n" +
	"\x13ReprioritizeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12*\n" +
	"\x11struggle_node_ids\x18\x02 \x03(\tR\x0fstruggleNodeIds2\x88\x03\n" +
	"\n" +
	"Curriculum\x12U\n" +
	"\fGeneratePath\x12!.wisdom.curriculum.v1.PathRequest\x1a\".wisdom.curriculum.v1.LearningPath\x12X\n" +
	"\x0fMapDependencies\x12\x1e.wisdom.curriculum.v1.NodeList\x1a%.wisdom.curriculum.v1.DependencyGraph\x12c\n" +
	"\x10AssignDifficulty\x12'.wisdom.curriculum.v1.DifficultyRequest\x1a&.wisdom.curriculum.v1.DifficultyResult\x12d\n" +
	"\x13ReprioritizeForUser\x12).wisdom.curriculum.v1.ReprioritizeRequest\x1a\".wisdom.curriculum.v1.LearningPathB9Z7github.com/google/wisdom/pkg/curriculum/v1;curriculumv1b\x06proto3"

var (
	file_proto_curriculum_proto_rawDescOnce sync.Once
	file_proto_curriculum_proto_rawDescData []byte
)

func file_proto_curriculum_proto_rawDescGZIP() []byte {
	file_proto_curriculum_proto_rawDescOnce.Do(func() {
		file_proto_curriculum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_curriculum_proto_rawDesc), len(file_proto_curriculum_proto_rawDesc)))
	})
	return file_proto_curriculum_proto_rawDescData
}

var file_proto_curriculum_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_curriculum_proto_goTypes = []any{
	(*PathRequest)(nil),         // 0: wisdom.curriculum.v1.PathRequest
	(*Module)(nil),              // 1: wisdom.curriculum.v1.Module
	(*LearningPath)(nil),        // 2: wisdom.curriculum.v1.LearningPath
	(*NodeList)(nil),            // 3: wisdom.curriculum.v1.NodeList
	(*Dependency)(nil),          // 4: wisdom.curriculum.v1.Dependency
	(*DependencyGraph)(nil),     // 5: wisdom.curriculum.v1.DependencyGraph
	(*DifficultyRequest)(nil),   // 6: wisdom.curriculum.v1.DifficultyRequest
	(*DifficultyResult)(nil),    // 7: wisdom.curriculum.v1.DifficultyResult
	(*ReprioritizeRequest)(nil), // 8: wisdom.curriculum.v1.ReprioritizeRequest
}
var file_proto_curriculum_proto_depIdxs = []int32{
	1, // 0: wisdom.curriculum.v1.LearningPath.modules:type_name -> wisdom.curriculum.v1.Module
	4, // 1: wisdom.curriculum.v1.DependencyGraph.edges:type_name -> wisdom.curriculum.v1.Dependency
	0, // 2: wisdom.curriculum.v1.Curriculum.GeneratePath:input_type -> wisdom.curriculum.v1.PathRequest
	3, // 3: wisdom.curriculum.v1.Curriculum.MapDependencies:input_type -> wisdom.curriculum.v1.NodeList
	6, // 4: wisdom.curriculum.v1.Curriculum.AssignDifficulty:input_type -> wisdom.curriculum.v1.DifficultyRequest
	8, // 5: wisdom.curriculum.v1.Curriculum.ReprioritizeForUser:input_type -> wisdom.curriculum.v1.ReprioritizeRequest
	2, // 6: wisdom.curriculum.v1.Curriculum.GeneratePath:output_type -> wisdom.curriculum.v1.LearningPath
	5, // 7: wisdom.curriculum.v1.Curriculum.MapDependencies:output_type -> wisdom.curriculum.v1.DependencyGraph
	7, // 8: wisdom.curriculum.v1.Curriculum.AssignDifficulty:output_type -> wisdom.curriculum.v1.DifficultyResult
	2, // 9: wisdom.curriculum.v1.Curriculum.ReprioritizeForUser:output_type -> wisdom.curriculum.v1.LearningPath
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_curriculum_proto_init() }
func file_proto_curriculum_proto_init() {
	if File_proto_curriculum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_curriculum_proto_rawDesc), len(file_proto_curriculum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_curriculum_proto_goTypes,
		DependencyIndexes: file_proto_curriculum_proto_depIdxs,
		MessageInfos:      file_proto_curriculum_proto_msgTypes,
	}.Build()
	File_proto_curriculum_proto = out.File
	file_proto_curriculum_proto_goTypes = nil
	file_proto_curriculum_proto_depIdxs = nil
}
