// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/curriculum.proto

package curriculumv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Curriculum_GeneratePath_FullMethodName        = "/wisdom.curriculum.v1.Curriculum/GeneratePath"
	Curriculum_MapDependencies_FullMethodName     = "/wisdom.curriculum.v1.Curriculum/MapDependencies"
	Curriculum_AssignDifficulty_FullMethodName    = "/wisdom.curriculum.v1.Curriculum/AssignDifficulty"
	Curriculum_ReprioritizeForUser_FullMethodName = "/wisdom.curriculum.v1.Curriculum/ReprioritizeForUser"
)

// CurriculumClient is the client API for Curriculum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Wisdom-Curriculum: transforms raw research into structured learning paths.
// The "Academic Dean" — organizes knowledge into a recursive hierarchy.
type CurriculumClient interface {
	// Generate a learning path for a topic at a given skill level.
	GeneratePath(ctx context.Context, in *PathRequest, opts ...grpc.CallOption) (*LearningPath, error)
	// Map prerequisite dependencies between a list of concept nodes.
	MapDependencies(ctx context.Context, in *NodeList, opts ...grpc.CallOption) (*DependencyGraph, error)
	// Assign a difficulty tier (1-5) to a module based on content analysis.
	AssignDifficulty(ctx context.Context, in *DifficultyRequest, opts ...grpc.CallOption) (*DifficultyResult, error)
	// Re-prioritize modules for a user based on their struggle signals.
	ReprioritizeForUser(ctx context.Context, in *ReprioritizeRequest, opts ...grpc.CallOption) (*LearningPath, error)
}

type curriculumClient struct {
	cc grpc.ClientConnInterface
}

func NewCurriculumClient(cc grpc.ClientConnInterface) CurriculumClient {
	return &curriculumClient{cc}
}

func (c *curriculumClient) GeneratePath(ctx context.Context, in *PathRequest, opts ...grpc.CallOption) (*LearningPath, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LearningPath)
	err := c.cc.Invoke(ctx, Curriculum_GeneratePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *curriculumClient) MapDependencies(ctx context.Context, in *NodeList, opts ...grpc.CallOption) (*DependencyGraph, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DependencyGraph)
	err := c.cc.Invoke(ctx, Curriculum_MapDependencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *curriculumClient) AssignDifficulty(ctx context.Context, in *DifficultyRequest, opts ...grpc.CallOption) (*DifficultyResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DifficultyResult)
	err := c.cc.Invoke(ctx, Curriculum_AssignDifficulty_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *curriculumClient) ReprioritizeForUser(ctx context.Context, in *ReprioritizeRequest, opts ...grpc.CallOption) (*LearningPath, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LearningPath)
	err := c.cc.Invoke(ctx, Curriculum_ReprioritizeForUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurriculumServer is the server API for Curriculum service.
// All implementations must embed UnimplementedCurriculumServer
// for forward compatibility.
//
// Wisdom-Curriculum: transforms raw research into structured learning paths.
// The "Academic Dean" — organizes knowledge into a recursive hierarchy.
type CurriculumServer interface {
	// Generate a learning path for a topic at a given skill level.
	GeneratePath(context.Context, *PathRequest) (*LearningPath, error)
	// Map prerequisite dependencies between a list of concept nodes.
	MapDependencies(context.Context, *NodeList) (*DependencyGraph, error)
	// Assign a difficulty tier (1-5) to a module based on content analysis.
	AssignDifficulty(context.Context, *DifficultyRequest) (*DifficultyResult, error)
	// Re-prioritize modules for a user based on their struggle signals.
	ReprioritizeForUser(context.Context, *ReprioritizeRequest) (*LearningPath, error)
	mustEmbedUnimplementedCurriculumServer()
}

// UnimplementedCurriculumServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCurriculumServer struct{}

func (UnimplementedCurriculumServer) GeneratePath(context.Context, *PathRequest) (*LearningPath, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePath not implemented")
}
func (UnimplementedCurriculumServer) MapDependencies(context.Context, *NodeList) (*DependencyGraph, error) {
	return nil, status.Error(codes.Unimplemented, "method MapDependencies not implemented")
}
func (UnimplementedCurriculumServer) AssignDifficulty(context.Context, *DifficultyRequest) (*DifficultyResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignDifficulty not implemented")
}
func (UnimplementedCurriculumServer) ReprioritizeForUser(context.Context, *ReprioritizeRequest) (*LearningPath, error) {
	return nil, status.Error(codes.Unimplemented, "method ReprioritizeForUser not implemented")
}
func (UnimplementedCurriculumServer) mustEmbedUnimplementedCurriculumServer() {}
func (UnimplementedCurriculumServer) testEmbeddedByValue()                    {}

// UnsafeCurriculumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurriculumServer will
// result in compilation errors.
type UnsafeCurriculumServer interface {
	mustEmbedUnimplementedCurriculumServer()
}

func RegisterCurriculumServer(s grpc.ServiceRegistrar, srv CurriculumServer) {
	// If the following call panics, it indicates UnimplementedCurriculumServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Curriculum_ServiceDesc, srv)
}

func _Curriculum_GeneratePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurriculumServer).GeneratePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Curriculum_GeneratePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurriculumServer).GeneratePath(ctx, req.(*PathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Curriculum_MapDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurriculumServer).MapDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Curriculum_MapDependencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurriculumServer).MapDependencies(ctx, req.(*NodeList))
	}
	return interceptor(ctx, in, info, handler)
}

func _Curriculum_AssignDifficulty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DifficultyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurriculumServer).AssignDifficulty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Curriculum_AssignDifficulty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurriculumServer).AssignDifficulty(ctx, req.(*DifficultyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Curriculum_ReprioritizeForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReprioritizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurriculumServer).ReprioritizeForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Curriculum_ReprioritizeForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurriculumServer).ReprioritizeForUser(ctx, req.(*ReprioritizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Curriculum_ServiceDesc is the grpc.ServiceDesc for Curriculum service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Curriculum_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wisdom.curriculum.v1.Curriculum",
	HandlerType: (*CurriculumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePath",
			Handler:    _Curriculum_GeneratePath_Handler,
		},
		{
			MethodName: "MapDependencies",
			Handler:    _Curriculum_MapDependencies_Handler,
		},
		{
			MethodName: "AssignDifficulty",
			Handler:    _Curriculum_AssignDifficulty_Handler,
		},
		{
			MethodName: "ReprioritizeForUser",
			Handler:    _Curriculum_ReprioritizeForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/curriculum.proto",
}
