// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/mastery.proto

package masteryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Mastery_RecordEngagement_FullMethodName   = "/wisdom.mastery.v1.Mastery/RecordEngagement"
	Mastery_GetWeaknesses_FullMethodName      = "/wisdom.mastery.v1.Mastery/GetWeaknesses"
	Mastery_GetStrengths_FullMethodName       = "/wisdom.mastery.v1.Mastery/GetStrengths"
	Mastery_SyncAnkiReviews_FullMethodName    = "/wisdom.mastery.v1.Mastery/SyncAnkiReviews"
	Mastery_GetDueCards_FullMethodName        = "/wisdom.mastery.v1.Mastery/GetDueCards"
	Mastery_ScheduleNextReview_FullMethodName = "/wisdom.mastery.v1.Mastery/ScheduleNextReview"
)

// MasteryClient is the client API for Mastery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Wisdom-Mastery: unified Trace (tracking) + Metabolism (scheduling) service.
// Trace and Metabolism are cohesive: interval calculation requires mastery state.
type MasteryClient interface {
	// --- Trace RPCs ---
	// Record a study event (Anki review, Portal flashcard, reading passage).
	RecordEngagement(ctx context.Context, in *TraceEvent, opts ...grpc.CallOption) (*TraceUpdate, error)
	// Get concepts the user is weakest on (lowest MasteryScore).
	GetWeaknesses(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ConceptList, error)
	// Get concepts the user has dominated (highest MasteryScore).
	GetStrengths(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ConceptList, error)
	// Sync a batch of Anki review grades into internal MasteryScores.
	SyncAnkiReviews(ctx context.Context, in *AnkiReviewBatch, opts ...grpc.CallOption) (*SyncResult, error)
	// --- Metabolism RPCs ---
	// Get all concepts due for review for a given user (feeds Portal SRS UI).
	GetDueCards(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*DueCardList, error)
	// After a review, compute and store the next review interval.
	ScheduleNextReview(ctx context.Context, in *ReviewOutcome, opts ...grpc.CallOption) (*ScheduleResult, error)
}

type masteryClient struct {
	cc grpc.ClientConnInterface
}

func NewMasteryClient(cc grpc.ClientConnInterface) MasteryClient {
	return &masteryClient{cc}
}

func (c *masteryClient) RecordEngagement(ctx context.Context, in *TraceEvent, opts ...grpc.CallOption) (*TraceUpdate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraceUpdate)
	err := c.cc.Invoke(ctx, Mastery_RecordEngagement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masteryClient) GetWeaknesses(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ConceptList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConceptList)
	err := c.cc.Invoke(ctx, Mastery_GetWeaknesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masteryClient) GetStrengths(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*ConceptList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConceptList)
	err := c.cc.Invoke(ctx, Mastery_GetStrengths_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masteryClient) SyncAnkiReviews(ctx context.Context, in *AnkiReviewBatch, opts ...grpc.CallOption) (*SyncResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResult)
	err := c.cc.Invoke(ctx, Mastery_SyncAnkiReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masteryClient) GetDueCards(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*DueCardList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DueCardList)
	err := c.cc.Invoke(ctx, Mastery_GetDueCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masteryClient) ScheduleNextReview(ctx context.Context, in *ReviewOutcome, opts ...grpc.CallOption) (*ScheduleResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleResult)
	err := c.cc.Invoke(ctx, Mastery_ScheduleNextReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasteryServer is the server API for Mastery service.
// All implementations must embed UnimplementedMasteryServer
// for forward compatibility.
//
// Wisdom-Mastery: unified Trace (tracking) + Metabolism (scheduling) service.
// Trace and Metabolism are cohesive: interval calculation requires mastery state.
type MasteryServer interface {
	// --- Trace RPCs ---
	// Record a study event (Anki review, Portal flashcard, reading passage).
	RecordEngagement(context.Context, *TraceEvent) (*TraceUpdate, error)
	// Get concepts the user is weakest on (lowest MasteryScore).
	GetWeaknesses(context.Context, *UserRequest) (*ConceptList, error)
	// Get concepts the user has dominated (highest MasteryScore).
	GetStrengths(context.Context, *UserRequest) (*ConceptList, error)
	// Sync a batch of Anki review grades into internal MasteryScores.
	SyncAnkiReviews(context.Context, *AnkiReviewBatch) (*SyncResult, error)
	// --- Metabolism RPCs ---
	// Get all concepts due for review for a given user (feeds Portal SRS UI).
	GetDueCards(context.Context, *UserRequest) (*DueCardList, error)
	// After a review, compute and store the next review interval.
	ScheduleNextReview(context.Context, *ReviewOutcome) (*ScheduleResult, error)
	mustEmbedUnimplementedMasteryServer()
}

// UnimplementedMasteryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasteryServer struct{}

func (UnimplementedMasteryServer) RecordEngagement(context.Context, *TraceEvent) (*TraceUpdate, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordEngagement not implemented")
}
func (UnimplementedMasteryServer) GetWeaknesses(context.Context, *UserRequest) (*ConceptList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeaknesses not implemented")
}
func (UnimplementedMasteryServer) GetStrengths(context.Context, *UserRequest) (*ConceptList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStrengths not implemented")
}
func (UnimplementedMasteryServer) SyncAnkiReviews(context.Context, *AnkiReviewBatch) (*SyncResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncAnkiReviews not implemented")
}
func (UnimplementedMasteryServer) GetDueCards(context.Context, *UserRequest) (*DueCardList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDueCards not implemented")
}
func (UnimplementedMasteryServer) ScheduleNextReview(context.Context, *ReviewOutcome) (*ScheduleResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ScheduleNextReview not implemented")
}
func (UnimplementedMasteryServer) mustEmbedUnimplementedMasteryServer() {}
func (UnimplementedMasteryServer) testEmbeddedByValue()                 {}

// UnsafeMasteryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasteryServer will
// result in compilation errors.
type UnsafeMasteryServer interface {
	mustEmbedUnimplementedMasteryServer()
}

func RegisterMasteryServer(s grpc.ServiceRegistrar, srv MasteryServer) {
	// If the following call panics, it indicates UnimplementedMasteryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Mastery_ServiceDesc, srv)
}

func _Mastery_RecordEngagement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasteryServer).RecordEngagement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mastery_RecordEngagement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasteryServer).RecordEngagement(ctx, req.(*TraceEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mastery_GetWeaknesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasteryServer).GetWeaknesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mastery_GetWeaknesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasteryServer).GetWeaknesses(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mastery_GetStrengths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasteryServer).GetStrengths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mastery_GetStrengths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasteryServer).GetStrengths(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mastery_SyncAnkiReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnkiReviewBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasteryServer).SyncAnkiReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mastery_SyncAnkiReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasteryServer).SyncAnkiReviews(ctx, req.(*AnkiReviewBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mastery_GetDueCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasteryServer).GetDueCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mastery_GetDueCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasteryServer).GetDueCards(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mastery_ScheduleNextReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewOutcome)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasteryServer).ScheduleNextReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mastery_ScheduleNextReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasteryServer).ScheduleNextReview(ctx, req.(*ReviewOutcome))
	}
	return interceptor(ctx, in, info, handler)
}

// Mastery_ServiceDesc is the grpc.ServiceDesc for Mastery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mastery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wisdom.mastery.v1.Mastery",
	HandlerType: (*MasteryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordEngagement",
			Handler:    _Mastery_RecordEngagement_Handler,
		},
		{
			MethodName: "GetWeaknesses",
			Handler:    _Mastery_GetWeaknesses_Handler,
		},
		{
			MethodName: "GetStrengths",
			Handler:    _Mastery_GetStrengths_Handler,
		},
		{
			MethodName: "SyncAnkiReviews",
			Handler:    _Mastery_SyncAnkiReviews_Handler,
		},
		{
			MethodName: "GetDueCards",
			Handler:    _Mastery_GetDueCards_Handler,
		},
		{
			MethodName: "ScheduleNextReview",
			Handler:    _Mastery_ScheduleNextReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mastery.proto",
}
