// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/mastery.proto

package masteryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TraceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // The concept node in Cortex
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`                // 1-5 scale (maps to Anki Again/Hard/Good/Easy/+)
	Context       string                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`             // "ANKI", "PORTAL", "READING", "CHAT"
	ReviewedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=reviewed_at,json=reviewedAt,proto3" json:"reviewed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceEvent) Reset() {
	*x = TraceEvent{}
	mi := &file_proto_mastery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceEvent) ProtoMessage() {}

func (x *TraceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mastery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceEvent.ProtoReflect.Descriptor instead.
func (*TraceEvent) Descriptor() ([]byte, []int) {
	return file_proto_mastery_proto_rawDescGZIP(), []int{0}
}

func (x *TraceEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TraceEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TraceEvent) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TraceEvent) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *TraceEvent) GetReviewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReviewedAt
	}
	return nil
}

type TraceUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MasteryScore  float64                `protobuf:"fixed64,2,opt,name=mastery_score,json=masteryScore,proto3" json:"mastery_score,omitempty"` // Clamped 0.0 to 1.0
	NewStatus     string                 `protobuf:"bytes,3,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`            // "FRAGILE", "LEARNING", "DOMINATED"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceUpdate) Reset() {
	*x = TraceUpdate{}
	mi := &file_proto_mastery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceUpdate) ProtoMessage() {}

func (x *TraceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mastery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceUpdate.ProtoReflect.Descriptor instead.
func (*TraceUpdate) Descriptor() ([]byte, []int) {
	return file_proto_mastery_proto_rawDescGZIP(), []int{1}
}

func (x *TraceUpdate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TraceUpdate) GetMasteryScore() float64 {
	if x != nil {
		return x.MasteryScore
	}
	return 0
}

func (x *TraceUpdate) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // Max results to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_proto_mastery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mastery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_proto_mastery_proto_rawDescGZIP(), []int{2}
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Concept struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	MasteryScore   float64                `protobuf:"fixed64,3,opt,name=mastery_score,json=masteryScore,proto3" json:"mastery_score,omitempty"`
	RetentionRate  float64                `protobuf:"fixed64,4,opt,name=retention_rate,json=retentionRate,proto3" json:"retention_rate,omitempty"` // Based on Ebbinghaus forgetting curve
	LastReviewedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_reviewed_at,json=lastReviewedAt,proto3" json:"last_reviewed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Concept) Reset() {
	*x = Concept{}
	mi := &file_proto_mastery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Concept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Concept) ProtoMessage() {}

func (x *Concept) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mastery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Concept.ProtoReflect.Descriptor instead.
func (*Concept) Descriptor() ([]byte, []int) {
	return file_proto_mastery_proto_rawDescGZIP(), []int{3}
}

func (x *Concept) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Concept) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Concept) GetMasteryScore() float64 {
	if x != nil {
		return x.MasteryScore
	}
	return 0
}

func (x *Concept) GetRetentionRate() float64 {
	if x != nil {
		return x.RetentionRate
	}
	return 0
}

func (x *Concept) GetLastReviewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastReviewedAt
	}
	return nil
}

type ConceptList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Concepts      []*Concept             `protobuf:"bytes,1,rep,name=concepts,proto3" json:"concepts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConceptList) Reset() {
	*x = ConceptList{}
	mi := &file_proto_mastery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConceptList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConceptList) ProtoMessage() {}

func (x *ConceptList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mastery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConceptList.ProtoReflect.Descriptor instead.
func (*ConceptList) Descriptor() ([]byte, []int) {
	return file_proto_mastery_proto_rawDescGZIP(), []int{4}
}

func (x *ConceptList) GetConcepts() []*Concept {
	if x != nil {
		return x.Concepts
	}
	return nil
}

// Batch sync from Anki polling (from Integrations service).
type AnkiReviewBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reviews       []*AnkiReview          `protobuf:"bytes,2,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnkiReviewBatch) Reset() {
	*x = AnkiReviewBatch{}
	mi := &file_proto_mastery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnkiReviewBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnkiReviewBatch) ProtoMessage() {}

func (x *AnkiReviewBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mastery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnkiReviewBatch.ProtoReflect.Descriptor instead.
func (*AnkiReviewBatch) Descriptor() ([]byte, []int) {
	return file_proto_mastery_proto_rawDescGZIP(), []int{5}
}

func (x *AnkiReviewBatch) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnkiReviewBatch) GetReviews() []*AnkiReview {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type AnkiReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnkiCardId    string                 `protobuf:"bytes,1,opt,name=anki_card_id,json=ankiCardId,proto3" json:"anki_card_id,omitempty"`       // Anki internal card ID
	WisdomNodeId  string                 `protobuf:"bytes,2,opt,name=wisdom_node_id,json=wisdomNodeId,proto3" json:"wisdom_node_id,omitempty"` // Matching Cortex node
	Grade         int32                  `protobuf:"varint,3,opt,name=grade,proto3" json:"grade,omitempty"`                                    // 1=Again, 2=Hard, 3=Good, 4=Easy
	ReviewId      string                 `protobuf:"bytes,4,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`               // Anki timestamp, used for deduplication
	ReviewedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=reviewed_at,json=reviewedAt,proto3" json:"reviewed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnkiReview) Reset() {
	*x = AnkiReview{}
	mi := &file_proto_mastery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnkiReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnkiReview) ProtoMessage() {}

func (x *AnkiReview) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mastery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnkiReview.ProtoReflect.Descriptor instead.
func (*AnkiReview) Descriptor() ([]byte, []int) {
	return file_proto_mastery_proto_rawDescGZIP(), []int{6}
}

func (x *AnkiReview) GetAnkiCardId() string {
	if x != nil {
		return x.AnkiCardId
	}
	return ""
}

func (x *AnkiReview) GetWisdomNodeId() string {
	if x != nil {
		return x.WisdomNodeId
	}
	return ""
}

func (x *AnkiReview) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *AnkiReview) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

func (x *AnkiReview) GetReviewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReviewedAt
	}
	return nil
}

type SyncResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncedCount   int32                  `protobuf:"varint,1,opt,name=synced_count,json=syncedCount,proto3" json:"synced_count,omitempty"`
	SkippedCount  int32                  `protobuf:"varint,2,opt,name=skipped_count,json=skippedCount,proto3" json:"skipped_count,omitempty"` // Already processed (dedup)
	ErrorCount    int32                  `protobuf:"varint,3,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResult) Reset() {
	*x = SyncResult{}
	mi := &file_proto_mastery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResult) ProtoMessage() {}

func (x *SyncResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mastery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResult.ProtoReflect.Descriptor instead.
func (*SyncResult) Descriptor() ([]byte, []int) {
	return file_proto_mastery_proto_rawDescGZIP(), []int{7}
}

func (x *SyncResult) GetSyncedCount() int32 {
	if x != nil {
		return x.SyncedCount
	}
	return 0
}

func (x *SyncResult) GetSkippedCount() int32 {
	if x != nil {
		return x.SkippedCount
	}
	return 0
}

func (x *SyncResult) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

type DueCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	MasteryScore  float64                `protobuf:"fixed64,3,opt,name=mastery_score,json=masteryScore,proto3" json:"mastery_score,omitempty"`
	DueAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DueCard) Reset() {
	*x = DueCard{}
	mi := &file_proto_mastery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DueCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DueCard) ProtoMessage() {}

func (x *DueCard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mastery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DueCard.ProtoReflect.Descriptor instead.
func (*DueCard) Descriptor() ([]byte, []int) {
	return file_proto_mastery_proto_rawDescGZIP(), []int{8}
}

func (x *DueCard) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DueCard) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DueCard) GetMasteryScore() float64 {
	if x != nil {
		return x.MasteryScore
	}
	return 0
}

func (x *DueCard) GetDueAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DueAt
	}
	return nil
}

type DueCardList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*DueCard             `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DueCardList) Reset() {
	*x = DueCardList{}
	mi := &file_proto_mastery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DueCardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DueCardList) ProtoMessage() {}

func (x *DueCardList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mastery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DueCardList.ProtoReflect.Descriptor instead.
func (*DueCardList) Descriptor() ([]byte, []int) {
	return file_proto_mastery_proto_rawDescGZIP(), []int{9}
}

func (x *DueCardList) GetCards() []*DueCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

type ReviewOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Grade         int32                  `protobuf:"varint,3,opt,name=grade,proto3" json:"grade,omitempty"`        // 1-4 Anki scale
	Scheduler     string                 `protobuf:"bytes,4,opt,name=scheduler,proto3" json:"scheduler,omitempty"` // "WISDOM" or "ANKI" — determines master scheduler
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewOutcome) Reset() {
	*x = ReviewOutcome{}
	mi := &file_proto_mastery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewOutcome) ProtoMessage() {}

func (x *ReviewOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mastery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewOutcome.ProtoReflect.Descriptor instead.
func (*ReviewOutcome) Descriptor() ([]byte, []int) {
	return file_proto_mastery_proto_rawDescGZIP(), []int{10}
}

func (x *ReviewOutcome) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReviewOutcome) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReviewOutcome) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *ReviewOutcome) GetScheduler() string {
	if x != nil {
		return x.Scheduler
	}
	return ""
}

type ScheduleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NextReviewAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=next_review_at,json=nextReviewAt,proto3" json:"next_review_at,omitempty"`
	IntervalDays  int32                  `protobuf:"varint,3,opt,name=interval_days,json=intervalDays,proto3" json:"interval_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleResult) Reset() {
	*x = ScheduleResult{}
	mi := &file_proto_mastery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleResult) ProtoMessage() {}

func (x *ScheduleResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mastery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleResult.ProtoReflect.Descriptor instead.
func (*ScheduleResult) Descriptor() ([]byte, []int) {
	return file_proto_mastery_proto_rawDescGZIP(), []int{11}
}

func (x *ScheduleResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ScheduleResult) GetNextReviewAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextReviewAt
	}
	return nil
}

func (x *ScheduleResult) GetIntervalDays() int32 {
	if x != nil {
		return x.IntervalDays
	}
	return 0
}

var File_proto_mastery_proto protoreflect.FileDescriptor

const file_proto_mastery_proto_rawDesc = "" +
	"\n" +
	"\x13proto/mastery.proto\x12\x11wisdom.mastery.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x01\n" +
	"\n" +
	"TraceEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\x12;\n" +
	"\vreviewed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reviewedAt\"j\n" +
	"\vTraceUpdate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\rmastery_score\x18\x02 \x01(\x01R\fmasteryScore\x12\x1d\n" +
	"\n" +
	"new_status\x18\x03 \x01(\tR\tnewStatus\"<\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xca\x01\n" +
	"\aConcept\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rmastery_score\x18\x03 \x01(\x01R\fmasteryScore\x12%\n" +
	"\x0eretention_rate\x18\x04 \x01(\x01R\rretentionRate\x12D\n" +
	"\x10last_reviewed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastReviewedAt\"E\n" +
	"\vConceptList\x126\n" +
	"\bconcepts\x18\x01 \x03(\v2\x1a.wisdom.mastery.v1.ConceptR\bconcepts\"c\n" +
	"\x0fAnkiReviewBatch\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x127\n" +
	"\areviews\x18\x02 \x03(\v2\x1d.wisdom.mastery.v1.AnkiReviewR\areviews\"\xc4\x01\n" +
	"\n" +
	"AnkiReview\x12 \n" +
	"\fanki_card_id\x18\x01 \x01(\tR\n" +
	"ankiCardId\x12$\n" +
	"\x0ewisdom_node_id\x18\x02 \x01(\tR\fwisdomNodeId\x12\x14\n" +
	"\x05grade\x18\x03 \x01(\x05R\x05grade\x12\x1b\n" +
	"\treview_id\x18\x04 \x01(\tR\breviewId\x12;\n" +
	"\vreviewed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reviewedAt\"u\n" +
	"\n" +
	"SyncResult\x12!\n" +
	"\fsynced_count\x18\x01 \x01(\x05R\vsyncedCount\x12#\n" +
	"\rskipped_count\x18\x02 \x01(\x05R\fskippedCount\x12\x1f\n" +
	"\verror_count\x18\x03 \x01(\x05R\n" +
	"errorCount\"\x90\x01\n" +
	"\aDueCard\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12#\n" +
	"\rmastery_score\x18\x03 \x01(\x01R\fmasteryScore\x121\n" +
	"\x06due_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05dueAt\"?\n" +
	"\vDueCardList\x120\n" +
	"\x05cards\x18\x01 \x03(\v2\x1a.wisdom.mastery.v1.DueCardR\x05cards\"u\n" +
	"\rReviewOutcome\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05grade\x18\x03 \x01(\x05R\x05grade\x12\x1c\n" +
	"\tscheduler\x18\x04 \x01(\tR\tscheduler\"\x90\x01\n" +
	"\x0eScheduleResult\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12@\n" +
	"\x0enext_review_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fnextReviewAt\x12#\n" +
	"\rinterval_days\x18\x03 \x01(\x05R\fintervalDays2\xfd\x03\n" +
	"\aMastery\x12Q\n" +
	"\x10RecordEngagement\x12\x1d.wisdom.mastery.v1.TraceEvent\x1a\x1e.wisdom.mastery.v1.TraceUpdate\x12O\n" +
	"\rGetWeaknesses\x12\x1e.wisdom.mastery.v1.UserRequest\x1a\x1e.wisdom.mastery.v1.ConceptList\x12N\n" +
	"\fGetStrengths\x12\x1e.wisdom.mastery.v1.UserRequest\x1a\x1e.wisdom.mastery.v1.ConceptList\x12T\n" +
	"\x0fSyncAnkiReviews\x12\".wisdom.mastery.v1.AnkiReviewBatch\x1a\x1d.wisdom.mastery.v1.SyncResult\x12M\n" +
	"\vGetDueCards\x12\x1e.wisdom.mastery.v1.UserRequest\x1a\x1e.wisdom.mastery.v1.DueCardList\x12Y\n" +
	"\x12ScheduleNextReview\x12 .wisdom.mastery.v1.ReviewOutcome\x1a!.wisdom.mastery.v1.ScheduleResultB3Z1github.com/google/wisdom/pkg/mastery/v1;masteryv1b\x06proto3"

var (
	file_proto_mastery_proto_rawDescOnce sync.Once
	file_proto_mastery_proto_rawDescData []byte
)

func file_proto_mastery_proto_rawDescGZIP() []byte {
	file_proto_mastery_proto_rawDescOnce.Do(func() {
		file_proto_mastery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mastery_proto_rawDesc), len(file_proto_mastery_proto_rawDesc)))
	})
	return file_proto_mastery_proto_rawDescData
}

var file_proto_mastery_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_mastery_proto_goTypes = []any{
	(*TraceEvent)(nil),            // 0: wisdom.mastery.v1.TraceEvent
	(*TraceUpdate)(nil),           // 1: wisdom.mastery.v1.TraceUpdate
	(*UserRequest)(nil),           // 2: wisdom.mastery.v1.UserRequest
	(*Concept)(nil),               // 3: wisdom.mastery.v1.Concept
	(*ConceptList)(nil),           // 4: wisdom.mastery.v1.ConceptList
	(*AnkiReviewBatch)(nil),       // 5: wisdom.mastery.v1.AnkiReviewBatch
	(*AnkiReview)(nil),            // 6: wisdom.mastery.v1.AnkiReview
	(*SyncResult)(nil),            // 7: wisdom.mastery.v1.SyncResult
	(*DueCard)(nil),               // 8: wisdom.mastery.v1.DueCard
	(*DueCardList)(nil),           // 9: wisdom.mastery.v1.DueCardList
	(*ReviewOutcome)(nil),         // 10: wisdom.mastery.v1.ReviewOutcome
	(*ScheduleResult)(nil),        // 11: wisdom.mastery.v1.ScheduleResult
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_proto_mastery_proto_depIdxs = []int32{
	12, // 0: wisdom.mastery.v1.TraceEvent.reviewed_at:type_name -> google.protobuf.Timestamp
	12, // 1: wisdom.mastery.v1.Concept.last_reviewed_at:type_name -> google.protobuf.Timestamp
	3,  // 2: wisdom.mastery.v1.ConceptList.concepts:type_name -> wisdom.mastery.v1.Concept
	6,  // 3: wisdom.mastery.v1.AnkiReviewBatch.reviews:type_name -> wisdom.mastery.v1.AnkiReview
	12, // 4: wisdom.mastery.v1.AnkiReview.reviewed_at:type_name -> google.protobuf.Timestamp
	12, // 5: wisdom.mastery.v1.DueCard.due_at:type_name -> google.protobuf.Timestamp
	8,  // 6: wisdom.mastery.v1.DueCardList.cards:type_name -> wisdom.mastery.v1.DueCard
	12, // 7: wisdom.mastery.v1.ScheduleResult.next_review_at:type_name -> google.protobuf.Timestamp
	0,  // 8: wisdom.mastery.v1.Mastery.RecordEngagement:input_type -> wisdom.mastery.v1.TraceEvent
	2,  // 9: wisdom.mastery.v1.Mastery.GetWeaknesses:input_type -> wisdom.mastery.v1.UserRequest
	2,  // 10: wisdom.mastery.v1.Mastery.GetStrengths:input_type -> wisdom.mastery.v1.UserRequest
	5,  // 11: wisdom.mastery.v1.Mastery.SyncAnkiReviews:input_type -> wisdom.mastery.v1.AnkiReviewBatch
	2,  // 12: wisdom.mastery.v1.Mastery.GetDueCards:input_type -> wisdom.mastery.v1.UserRequest
	10, // 13: wisdom.mastery.v1.Mastery.ScheduleNextReview:input_type -> wisdom.mastery.v1.ReviewOutcome
	1,  // 14: wisdom.mastery.v1.Mastery.RecordEngagement:output_type -> wisdom.mastery.v1.TraceUpdate
	4,  // 15: wisdom.mastery.v1.Mastery.GetWeaknesses:output_type -> wisdom.mastery.v1.ConceptList
	4,  // 16: wisdom.mastery.v1.Mastery.GetStrengths:output_type -> wisdom.mastery.v1.ConceptList
	7,  // 17: wisdom.mastery.v1.Mastery.SyncAnkiReviews:output_type -> wisdom.mastery.v1.SyncResult
	9,  // 18: wisdom.mastery.v1.Mastery.GetDueCards:output_type -> wisdom.mastery.v1.DueCardList
	11, // 19: wisdom.mastery.v1.Mastery.ScheduleNextReview:output_type -> wisdom.mastery.v1.ScheduleResult
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_mastery_proto_init() }
func file_proto_mastery_proto_init() {
	if File_proto_mastery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mastery_proto_rawDesc), len(file_proto_mastery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mastery_proto_goTypes,
		DependencyIndexes: file_proto_mastery_proto_depIdxs,
		MessageInfos:      file_proto_mastery_proto_msgTypes,
	}.Build()
	File_proto_mastery_proto = out.File
	file_proto_mastery_proto_goTypes = nil
	file_proto_mastery_proto_depIdxs = nil
}
