// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/pubsub_events.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The outer envelope for every Pub/Sub message.
type WisdomEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EventId     string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // UUID v4
	Topic       string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`                    // e.g., "wisdom.knowledge.ingested"
	UserId      string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PublishedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	// The actual payload — one of the message types below, serialized as JSON.
	Payload       *structpb.Struct `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WisdomEvent) Reset() {
	*x = WisdomEvent{}
	mi := &file_proto_pubsub_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WisdomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WisdomEvent) ProtoMessage() {}

func (x *WisdomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WisdomEvent.ProtoReflect.Descriptor instead.
func (*WisdomEvent) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_events_proto_rawDescGZIP(), []int{0}
}

func (x *WisdomEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WisdomEvent) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *WisdomEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WisdomEvent) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *WisdomEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

// --- wisdom.knowledge.ingested ---
// Triggered by Researcher when a scrape job finishes.
// Subscriber: Cortex (triggers indexing and embedding).
type KnowledgeIngestedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // URL or GCS URI
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	NodeCount     int32                  `protobuf:"varint,4,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"` // Number of new nodes created in Cortex
	GcsUri        string                 `protobuf:"bytes,5,opt,name=gcs_uri,json=gcsUri,proto3" json:"gcs_uri,omitempty"`           // URI to raw content in GCS (if large)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeIngestedEvent) Reset() {
	*x = KnowledgeIngestedEvent{}
	mi := &file_proto_pubsub_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeIngestedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeIngestedEvent) ProtoMessage() {}

func (x *KnowledgeIngestedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeIngestedEvent.ProtoReflect.Descriptor instead.
func (*KnowledgeIngestedEvent) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_events_proto_rawDescGZIP(), []int{1}
}

func (x *KnowledgeIngestedEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *KnowledgeIngestedEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *KnowledgeIngestedEvent) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *KnowledgeIngestedEvent) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *KnowledgeIngestedEvent) GetGcsUri() string {
	if x != nil {
		return x.GcsUri
	}
	return ""
}

// --- wisdom.learning.path_created ---
// Triggered by Curriculum when a new learning path is generated.
// Subscriber: Mastery (initializes progress markers per concept).
type LearningPathCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathId        string                 `protobuf:"bytes,1,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModuleIds     []string               `protobuf:"bytes,4,rep,name=module_ids,json=moduleIds,proto3" json:"module_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LearningPathCreatedEvent) Reset() {
	*x = LearningPathCreatedEvent{}
	mi := &file_proto_pubsub_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LearningPathCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LearningPathCreatedEvent) ProtoMessage() {}

func (x *LearningPathCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LearningPathCreatedEvent.ProtoReflect.Descriptor instead.
func (*LearningPathCreatedEvent) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_events_proto_rawDescGZIP(), []int{2}
}

func (x *LearningPathCreatedEvent) GetPathId() string {
	if x != nil {
		return x.PathId
	}
	return ""
}

func (x *LearningPathCreatedEvent) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *LearningPathCreatedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LearningPathCreatedEvent) GetModuleIds() []string {
	if x != nil {
		return x.ModuleIds
	}
	return nil
}

// --- wisdom.user.struggle_detected ---
// Triggered by Mastery when MasteryScore drops below 0.3 (FRAGILE status).
// Subscriber: Curriculum (re-prioritizes the user's learning path).
type StruggleDetectedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeTitle     string                 `protobuf:"bytes,3,opt,name=node_title,json=nodeTitle,proto3" json:"node_title,omitempty"`
	MasteryScore  float64                `protobuf:"fixed64,4,opt,name=mastery_score,json=masteryScore,proto3" json:"mastery_score,omitempty"`
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StruggleDetectedEvent) Reset() {
	*x = StruggleDetectedEvent{}
	mi := &file_proto_pubsub_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StruggleDetectedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StruggleDetectedEvent) ProtoMessage() {}

func (x *StruggleDetectedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StruggleDetectedEvent.ProtoReflect.Descriptor instead.
func (*StruggleDetectedEvent) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_events_proto_rawDescGZIP(), []int{3}
}

func (x *StruggleDetectedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StruggleDetectedEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StruggleDetectedEvent) GetNodeTitle() string {
	if x != nil {
		return x.NodeTitle
	}
	return ""
}

func (x *StruggleDetectedEvent) GetMasteryScore() float64 {
	if x != nil {
		return x.MasteryScore
	}
	return 0
}

func (x *StruggleDetectedEvent) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

// --- wisdom.memory.consolidation ---
// Triggered by ADK Router after GenerateMemories completes.
// Subscriber: Portal WebSocket bridge (notifies user of memory update).
type MemoryConsolidationEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FactsExtracted int32                  `protobuf:"varint,2,opt,name=facts_extracted,json=factsExtracted,proto3" json:"facts_extracted,omitempty"`
	Topics         []string               `protobuf:"bytes,3,rep,name=topics,proto3" json:"topics,omitempty"` // e.g., ["CHESS_OPENINGS", "ELO_PROGRESS"]
	AgentName      string                 `protobuf:"bytes,4,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryConsolidationEvent) Reset() {
	*x = MemoryConsolidationEvent{}
	mi := &file_proto_pubsub_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryConsolidationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryConsolidationEvent) ProtoMessage() {}

func (x *MemoryConsolidationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryConsolidationEvent.ProtoReflect.Descriptor instead.
func (*MemoryConsolidationEvent) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_events_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryConsolidationEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MemoryConsolidationEvent) GetFactsExtracted() int32 {
	if x != nil {
		return x.FactsExtracted
	}
	return 0
}

func (x *MemoryConsolidationEvent) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *MemoryConsolidationEvent) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

// --- wisdom.integrations.sync_ready ---
// Triggered by Integrations when PENDING_SYNC items become available for retry.
// Subscriber: Portal WebSocket bridge (shows notification in Mission Control).
type SyncReadyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PendingNotes  int32                  `protobuf:"varint,2,opt,name=pending_notes,json=pendingNotes,proto3" json:"pending_notes,omitempty"`
	PendingCards  int32                  `protobuf:"varint,3,opt,name=pending_cards,json=pendingCards,proto3" json:"pending_cards,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"` // e.g., "5 Anki cards pending. Please open Anki to sync."
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncReadyEvent) Reset() {
	*x = SyncReadyEvent{}
	mi := &file_proto_pubsub_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncReadyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReadyEvent) ProtoMessage() {}

func (x *SyncReadyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pubsub_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReadyEvent.ProtoReflect.Descriptor instead.
func (*SyncReadyEvent) Descriptor() ([]byte, []int) {
	return file_proto_pubsub_events_proto_rawDescGZIP(), []int{5}
}

func (x *SyncReadyEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncReadyEvent) GetPendingNotes() int32 {
	if x != nil {
		return x.PendingNotes
	}
	return 0
}

func (x *SyncReadyEvent) GetPendingCards() int32 {
	if x != nil {
		return x.PendingCards
	}
	return 0
}

func (x *SyncReadyEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_pubsub_events_proto protoreflect.FileDescriptor

const file_proto_pubsub_events_proto_rawDesc = "" +
	"\n" +
	"\x19proto/pubsub_events.proto\x12\x10wisdom.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc9\x01\n" +
	"\vWisdomEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12=\n" +
	"\fpublished_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\"\x97\x01\n" +
	"\x16KnowledgeIngestedEvent\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"node_count\x18\x04 \x01(\x05R\tnodeCount\x12\x17\n" +
	"\agcs_uri\x18\x05 \x01(\tR\x06gcsUri\"\x81\x01\n" +
	"\x18LearningPathCreatedEvent\x12\x17\n" +
	"\apath_id\x18\x01 \x01(\tR\x06pathId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"module_ids\x18\x04 \x03(\tR\tmoduleIds\"\xa5\x01\n" +
	"\x15StruggleDetectedEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"node_title\x18\x03 \x01(\tR\tnodeTitle\x12#\n" +
	"\rmastery_score\x18\x04 \x01(\x01R\fmasteryScore\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\"\x99\x01\n" +
	"\x18MemoryConsolidationEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0ffacts_extracted\x18\x02 \x01(\x05R\x0efactsExtracted\x12\x16\n" +
	"\x06topics\x18\x03 \x03(\tR\x06topics\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x04 \x01(\tR\tagentName\"\x8d\x01\n" +
	"\x0eSyncReadyEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rpending_notes\x18\x02 \x01(\x05R\fpendingNotes\x12#\n" +
	"\rpending_cards\x18\x03 \x01(\x05R\fpendingCards\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessageB1Z/github.com/google/wisdom/pkg/events/v1;eventsv1b\x06proto3"

var (
	file_proto_pubsub_events_proto_rawDescOnce sync.Once
	file_proto_pubsub_events_proto_rawDescData []byte
)

func file_proto_pubsub_events_proto_rawDescGZIP() []byte {
	file_proto_pubsub_events_proto_rawDescOnce.Do(func() {
		file_proto_pubsub_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pubsub_events_proto_rawDesc), len(file_proto_pubsub_events_proto_rawDesc)))
	})
	return file_proto_pubsub_events_proto_rawDescData
}

var file_proto_pubsub_events_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_pubsub_events_proto_goTypes = []any{
	(*WisdomEvent)(nil),              // 0: wisdom.events.v1.WisdomEvent
	(*KnowledgeIngestedEvent)(nil),   // 1: wisdom.events.v1.KnowledgeIngestedEvent
	(*LearningPathCreatedEvent)(nil), // 2: wisdom.events.v1.LearningPathCreatedEvent
	(*StruggleDetectedEvent)(nil),    // 3: wisdom.events.v1.StruggleDetectedEvent
	(*MemoryConsolidationEvent)(nil), // 4: wisdom.events.v1.MemoryConsolidationEvent
	(*SyncReadyEvent)(nil),           // 5: wisdom.events.v1.SyncReadyEvent
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
	(*structpb.Struct)(nil),          // 7: google.protobuf.Struct
}
var file_proto_pubsub_events_proto_depIdxs = []int32{
	6, // 0: wisdom.events.v1.WisdomEvent.published_at:type_name -> google.protobuf.Timestamp
	7, // 1: wisdom.events.v1.WisdomEvent.payload:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_pubsub_events_proto_init() }
func file_proto_pubsub_events_proto_init() {
	if File_proto_pubsub_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pubsub_events_proto_rawDesc), len(file_proto_pubsub_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_pubsub_events_proto_goTypes,
		DependencyIndexes: file_proto_pubsub_events_proto_depIdxs,
		MessageInfos:      file_proto_pubsub_events_proto_msgTypes,
	}.Build()
	File_proto_pubsub_events_proto = out.File
	file_proto_pubsub_events_proto_goTypes = nil
	file_proto_pubsub_events_proto_depIdxs = nil
}
