// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/integrations.proto

package integrationsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnkiCardType int32

const (
	AnkiCardType_BASIC AnkiCardType = 0 // Wisdom-Basic schema (front/back)
	AnkiCardType_CLOZE AnkiCardType = 1 // Wisdom-Cloze schema (for language/code)
)

// Enum value maps for AnkiCardType.
var (
	AnkiCardType_name = map[int32]string{
		0: "BASIC",
		1: "CLOZE",
	}
	AnkiCardType_value = map[string]int32{
		"BASIC": 0,
		"CLOZE": 1,
	}
)

func (x AnkiCardType) Enum() *AnkiCardType {
	p := new(AnkiCardType)
	*p = x
	return p
}

func (x AnkiCardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnkiCardType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_integrations_proto_enumTypes[0].Descriptor()
}

func (AnkiCardType) Type() protoreflect.EnumType {
	return &file_proto_integrations_proto_enumTypes[0]
}

func (x AnkiCardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnkiCardType.Descriptor instead.
func (AnkiCardType) EnumDescriptor() ([]byte, []int) {
	return file_proto_integrations_proto_rawDescGZIP(), []int{0}
}

type NoteMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Aliases       []string               `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	MasteryScore  float64                `protobuf:"fixed64,4,opt,name=mastery_score,json=masteryScore,proto3" json:"mastery_score,omitempty"`
	Domain        string                 `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"` // "chess", "technology", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteMetadata) Reset() {
	*x = NoteMetadata{}
	mi := &file_proto_integrations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteMetadata) ProtoMessage() {}

func (x *NoteMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integrations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteMetadata.ProtoReflect.Descriptor instead.
func (*NoteMetadata) Descriptor() ([]byte, []int) {
	return file_proto_integrations_proto_rawDescGZIP(), []int{0}
}

func (x *NoteMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoteMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *NoteMetadata) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *NoteMetadata) GetMasteryScore() float64 {
	if x != nil {
		return x.MasteryScore
	}
	return 0
}

func (x *NoteMetadata) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type NoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"` // Which Expert Agent is sending this
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Metadata      *NoteMetadata          `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`                         // Full Markdown content with Wikilinks
	Relationships []string               `protobuf:"bytes,5,rep,name=relationships,proto3" json:"relationships,omitempty"`             // e.g., ["[[React Hooks]]", "[[Fiber]]"]
	TargetPath    string                 `protobuf:"bytes,6,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"` // e.g., "Vault/Tech/React/RSC.md"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteRequest) Reset() {
	*x = NoteRequest{}
	mi := &file_proto_integrations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteRequest) ProtoMessage() {}

func (x *NoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integrations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteRequest.ProtoReflect.Descriptor instead.
func (*NoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_integrations_proto_rawDescGZIP(), []int{1}
}

func (x *NoteRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *NoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NoteRequest) GetMetadata() *NoteMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NoteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NoteRequest) GetRelationships() []string {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *NoteRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

type CardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeckName      string                 `protobuf:"bytes,3,opt,name=deck_name,json=deckName,proto3" json:"deck_name,omitempty"` // e.g., "Wisdom::Chess::Tactics"
	CardType      AnkiCardType           `protobuf:"varint,4,opt,name=card_type,json=cardType,proto3,enum=wisdom.integrations.v1.AnkiCardType" json:"card_type,omitempty"`
	Front         string                 `protobuf:"bytes,5,opt,name=front,proto3" json:"front,omitempty"`                          // Front of card (Markdown/HTML)
	Back          string                 `protobuf:"bytes,6,opt,name=back,proto3" json:"back,omitempty"`                            // Back with answer + [[Wikilink]] to Obsidian source
	ClozeText     string                 `protobuf:"bytes,7,opt,name=cloze_text,json=clozeText,proto3" json:"cloze_text,omitempty"` // For CLOZE type: text with {{c1::...}} deletions
	Extra         string                 `protobuf:"bytes,8,opt,name=extra,proto3" json:"extra,omitempty"`                          // Grammar rules or additional context
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	WisdomNodeId  string                 `protobuf:"bytes,10,opt,name=wisdom_node_id,json=wisdomNodeId,proto3" json:"wisdom_node_id,omitempty"` // Cortex node ID for mastery sync
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardRequest) Reset() {
	*x = CardRequest{}
	mi := &file_proto_integrations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardRequest) ProtoMessage() {}

func (x *CardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integrations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardRequest.ProtoReflect.Descriptor instead.
func (*CardRequest) Descriptor() ([]byte, []int) {
	return file_proto_integrations_proto_rawDescGZIP(), []int{2}
}

func (x *CardRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *CardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CardRequest) GetDeckName() string {
	if x != nil {
		return x.DeckName
	}
	return ""
}

func (x *CardRequest) GetCardType() AnkiCardType {
	if x != nil {
		return x.CardType
	}
	return AnkiCardType_BASIC
}

func (x *CardRequest) GetFront() string {
	if x != nil {
		return x.Front
	}
	return ""
}

func (x *CardRequest) GetBack() string {
	if x != nil {
		return x.Back
	}
	return ""
}

func (x *CardRequest) GetClozeText() string {
	if x != nil {
		return x.ClozeText
	}
	return ""
}

func (x *CardRequest) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *CardRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CardRequest) GetWisdomNodeId() string {
	if x != nil {
		return x.WisdomNodeId
	}
	return ""
}

type IntegrationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"` // Obsidian note path or Anki card ID
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                           // "SYNCED", "PENDING_SYNC", "ERROR"
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationResult) Reset() {
	*x = IntegrationResult{}
	mi := &file_proto_integrations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationResult) ProtoMessage() {}

func (x *IntegrationResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integrations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationResult.ProtoReflect.Descriptor instead.
func (*IntegrationResult) Descriptor() ([]byte, []int) {
	return file_proto_integrations_proto_rawDescGZIP(), []int{3}
}

func (x *IntegrationResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IntegrationResult) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *IntegrationResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IntegrationResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type QueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRequest) Reset() {
	*x = QueueRequest{}
	mi := &file_proto_integrations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRequest) ProtoMessage() {}

func (x *QueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integrations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRequest.ProtoReflect.Descriptor instead.
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_integrations_proto_rawDescGZIP(), []int{4}
}

func (x *QueueRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PendingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemType      string                 `protobuf:"bytes,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`          // "NOTE" or "CARD"
	TargetApp     string                 `protobuf:"bytes,3,opt,name=target_app,json=targetApp,proto3" json:"target_app,omitempty"`       // "OBSIDIAN", "ANKI", "LOGSEQ"
	PayloadJson   string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"` // Serialized original request
	RetryCount    int32                  `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	QueuedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=queued_at,json=queuedAt,proto3" json:"queued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingItem) Reset() {
	*x = PendingItem{}
	mi := &file_proto_integrations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingItem) ProtoMessage() {}

func (x *PendingItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integrations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingItem.ProtoReflect.Descriptor instead.
func (*PendingItem) Descriptor() ([]byte, []int) {
	return file_proto_integrations_proto_rawDescGZIP(), []int{5}
}

func (x *PendingItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *PendingItem) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *PendingItem) GetTargetApp() string {
	if x != nil {
		return x.TargetApp
	}
	return ""
}

func (x *PendingItem) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *PendingItem) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *PendingItem) GetQueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.QueuedAt
	}
	return nil
}

type PendingQueue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PendingItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingQueue) Reset() {
	*x = PendingQueue{}
	mi := &file_proto_integrations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingQueue) ProtoMessage() {}

func (x *PendingQueue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integrations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingQueue.ProtoReflect.Descriptor instead.
func (*PendingQueue) Descriptor() ([]byte, []int) {
	return file_proto_integrations_proto_rawDescGZIP(), []int{6}
}

func (x *PendingQueue) GetItems() []*PendingItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PendingQueue) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type RetryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succeeded     int32                  `protobuf:"varint,1,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Failed        int32                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	StillPending  int32                  `protobuf:"varint,3,opt,name=still_pending,json=stillPending,proto3" json:"still_pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryResult) Reset() {
	*x = RetryResult{}
	mi := &file_proto_integrations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryResult) ProtoMessage() {}

func (x *RetryResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integrations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryResult.ProtoReflect.Descriptor instead.
func (*RetryResult) Descriptor() ([]byte, []int) {
	return file_proto_integrations_proto_rawDescGZIP(), []int{7}
}

func (x *RetryResult) GetSucceeded() int32 {
	if x != nil {
		return x.Succeeded
	}
	return 0
}

func (x *RetryResult) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *RetryResult) GetStillPending() int32 {
	if x != nil {
		return x.StillPending
	}
	return 0
}

type AnkiReviewEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnkiCardId    string                 `protobuf:"bytes,1,opt,name=anki_card_id,json=ankiCardId,proto3" json:"anki_card_id,omitempty"`
	WisdomNodeId  string                 `protobuf:"bytes,2,opt,name=wisdom_node_id,json=wisdomNodeId,proto3" json:"wisdom_node_id,omitempty"`
	Grade         int32                  `protobuf:"varint,3,opt,name=grade,proto3" json:"grade,omitempty"`                      // 1=Again, 2=Hard, 3=Good, 4=Easy
	ReviewId      string                 `protobuf:"bytes,4,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"` // Anki timestamp — used for deduplication
	ReviewedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=reviewed_at,json=reviewedAt,proto3" json:"reviewed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnkiReviewEntry) Reset() {
	*x = AnkiReviewEntry{}
	mi := &file_proto_integrations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnkiReviewEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnkiReviewEntry) ProtoMessage() {}

func (x *AnkiReviewEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integrations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnkiReviewEntry.ProtoReflect.Descriptor instead.
func (*AnkiReviewEntry) Descriptor() ([]byte, []int) {
	return file_proto_integrations_proto_rawDescGZIP(), []int{8}
}

func (x *AnkiReviewEntry) GetAnkiCardId() string {
	if x != nil {
		return x.AnkiCardId
	}
	return ""
}

func (x *AnkiReviewEntry) GetWisdomNodeId() string {
	if x != nil {
		return x.WisdomNodeId
	}
	return ""
}

func (x *AnkiReviewEntry) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *AnkiReviewEntry) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

func (x *AnkiReviewEntry) GetReviewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReviewedAt
	}
	return nil
}

type AnkiReviewBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reviews       []*AnkiReviewEntry     `protobuf:"bytes,2,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnkiReviewBatch) Reset() {
	*x = AnkiReviewBatch{}
	mi := &file_proto_integrations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnkiReviewBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnkiReviewBatch) ProtoMessage() {}

func (x *AnkiReviewBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integrations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnkiReviewBatch.ProtoReflect.Descriptor instead.
func (*AnkiReviewBatch) Descriptor() ([]byte, []int) {
	return file_proto_integrations_proto_rawDescGZIP(), []int{9}
}

func (x *AnkiReviewBatch) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnkiReviewBatch) GetReviews() []*AnkiReviewEntry {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type AnkiSyncResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncedCount   int32                  `protobuf:"varint,1,opt,name=synced_count,json=syncedCount,proto3" json:"synced_count,omitempty"`
	SkippedCount  int32                  `protobuf:"varint,2,opt,name=skipped_count,json=skippedCount,proto3" json:"skipped_count,omitempty"` // Deduplication hits
	ErrorCount    int32                  `protobuf:"varint,3,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnkiSyncResult) Reset() {
	*x = AnkiSyncResult{}
	mi := &file_proto_integrations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnkiSyncResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnkiSyncResult) ProtoMessage() {}

func (x *AnkiSyncResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_integrations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnkiSyncResult.ProtoReflect.Descriptor instead.
func (*AnkiSyncResult) Descriptor() ([]byte, []int) {
	return file_proto_integrations_proto_rawDescGZIP(), []int{10}
}

func (x *AnkiSyncResult) GetSyncedCount() int32 {
	if x != nil {
		return x.SyncedCount
	}
	return 0
}

func (x *AnkiSyncResult) GetSkippedCount() int32 {
	if x != nil {
		return x.SkippedCount
	}
	return 0
}

func (x *AnkiSyncResult) GetErrorCount() int32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

var File_proto_integrations_proto protoreflect.FileDescriptor

const file_proto_integrations_proto_rawDesc = "" +
	"\n" +
	"\x18proto/integrations.proto\x12\x16wisdom.integrations.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x01\n" +
	"\fNoteMetadata\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x18\n" +
	"\aaliases\x18\x03 \x03(\tR\aaliases\x12#\n" +
	"\rmastery_score\x18\x04 \x01(\x01R\fmasteryScore\x12\x16\n" +
	"\x06domain\x18\x05 \x01(\tR\x06domain\"\xe8\x01\n" +
	"\vNoteRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12@\n" +
	"\bmetadata\x18\x03 \x01(\v2$.wisdom.integrations.v1.NoteMetadataR\bmetadata\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12$\n" +
	"\rrelationships\x18\x05 \x03(\tR\rrelationships\x12\x1f\n" +
	"\vtarget_path\x18\x06 \x01(\tR\n" +
	"targetPath\"\xbe\x02\n" +
	"\vCardRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdeck_name\x18\x03 \x01(\tR\bdeckName\x12A\n" +
	"\tcard_type\x18\x04 \x01(\x0e2$.wisdom.integrations.v1.AnkiCardTypeR\bcardType\x12\x14\n" +
	"\x05front\x18\x05 \x01(\tR\x05front\x12\x12\n" +
	"\x04back\x18\x06 \x01(\tR\x04back\x12\x1d\n" +
	"\n" +
	"cloze_text\x18\a \x01(\tR\tclozeText\x12\x14\n" +
	"\x05extra\x18\b \x01(\tR\x05extra\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12$\n" +
	"\x0ewisdom_node_id\x18\n" +
	" \x01(\tR\fwisdomNodeId\"\x8b\x01\n" +
	"\x11IntegrationResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"'\n" +
	"\fQueueRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xdf\x01\n" +
	"\vPendingItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_type\x18\x02 \x01(\tR\bitemType\x12\x1d\n" +
	"\n" +
	"target_app\x18\x03 \x01(\tR\ttargetApp\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\x12\x1f\n" +
	"\vretry_count\x18\x05 \x01(\x05R\n" +
	"retryCount\x127\n" +
	"\tqueued_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bqueuedAt\"j\n" +
	"\fPendingQueue\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.wisdom.integrations.v1.PendingItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"h\n" +
	"\vRetryResult\x12\x1c\n" +
	"\tsucceeded\x18\x01 \x01(\x05R\tsucceeded\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x05R\x06failed\x12#\n" +
	"\rstill_pending\x18\x03 \x01(\x05R\fstillPending\"\xc9\x01\n" +
	"\x0fAnkiReviewEntry\x12 \n" +
	"\fanki_card_id\x18\x01 \x01(\tR\n" +
	"ankiCardId\x12$\n" +
	"\x0ewisdom_node_id\x18\x02 \x01(\tR\fwisdomNodeId\x12\x14\n" +
	"\x05grade\x18\x03 \x01(\x05R\x05grade\x12\x1b\n" +
	"\treview_id\x18\x04 \x01(\tR\breviewId\x12;\n" +
	"\vreviewed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"reviewedAt\"m\n" +
	"\x0fAnkiReviewBatch\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12A\n" +
	"\areviews\x18\x02 \x03(\v2'.wisdom.integrations.v1.AnkiReviewEntryR\areviews\"y\n" +
	"\x0eAnkiSyncResult\x12!\n" +
	"\fsynced_count\x18\x01 \x01(\x05R\vsyncedCount\x12#\n" +
	"\rskipped_count\x18\x02 \x01(\x05R\fskippedCount\x12\x1f\n" +
	"\verror_count\x18\x03 \x01(\x05R\n" +
	"errorCount*$\n" +
	"\fAnkiCardType\x12\t\n" +
	"\x05BASIC\x10\x00\x12\t\n" +
	"\x05CLOZE\x10\x012\xef\x03\n" +
	"\fIntegrations\x12\\\n" +
	"\n" +
	"CreateNote\x12#.wisdom.integrations.v1.NoteRequest\x1a).wisdom.integrations.v1.IntegrationResult\x12\\\n" +
	"\n" +
	"CreateCard\x12#.wisdom.integrations.v1.CardRequest\x1a).wisdom.integrations.v1.IntegrationResult\x12]\n" +
	"\x0fGetPendingQueue\x12$.wisdom.integrations.v1.QueueRequest\x1a$.wisdom.integrations.v1.PendingQueue\x12]\n" +
	"\x10RetryPendingSync\x12$.wisdom.integrations.v1.QueueRequest\x1a#.wisdom.integrations.v1.RetryResult\x12e\n" +
	"\x12ProcessAnkiReviews\x12'.wisdom.integrations.v1.AnkiReviewBatch\x1a&.wisdom.integrations.v1.AnkiSyncResultB=Z;github.com/google/wisdom/pkg/integrations/v1;integrationsv1b\x06proto3"

var (
	file_proto_integrations_proto_rawDescOnce sync.Once
	file_proto_integrations_proto_rawDescData []byte
)

func file_proto_integrations_proto_rawDescGZIP() []byte {
	file_proto_integrations_proto_rawDescOnce.Do(func() {
		file_proto_integrations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_integrations_proto_rawDesc), len(file_proto_integrations_proto_rawDesc)))
	})
	return file_proto_integrations_proto_rawDescData
}

var file_proto_integrations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_integrations_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_integrations_proto_goTypes = []any{
	(AnkiCardType)(0),             // 0: wisdom.integrations.v1.AnkiCardType
	(*NoteMetadata)(nil),          // 1: wisdom.integrations.v1.NoteMetadata
	(*NoteRequest)(nil),           // 2: wisdom.integrations.v1.NoteRequest
	(*CardRequest)(nil),           // 3: wisdom.integrations.v1.CardRequest
	(*IntegrationResult)(nil),     // 4: wisdom.integrations.v1.IntegrationResult
	(*QueueRequest)(nil),          // 5: wisdom.integrations.v1.QueueRequest
	(*PendingItem)(nil),           // 6: wisdom.integrations.v1.PendingItem
	(*PendingQueue)(nil),          // 7: wisdom.integrations.v1.PendingQueue
	(*RetryResult)(nil),           // 8: wisdom.integrations.v1.RetryResult
	(*AnkiReviewEntry)(nil),       // 9: wisdom.integrations.v1.AnkiReviewEntry
	(*AnkiReviewBatch)(nil),       // 10: wisdom.integrations.v1.AnkiReviewBatch
	(*AnkiSyncResult)(nil),        // 11: wisdom.integrations.v1.AnkiSyncResult
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_proto_integrations_proto_depIdxs = []int32{
	1,  // 0: wisdom.integrations.v1.NoteRequest.metadata:type_name -> wisdom.integrations.v1.NoteMetadata
	0,  // 1: wisdom.integrations.v1.CardRequest.card_type:type_name -> wisdom.integrations.v1.AnkiCardType
	12, // 2: wisdom.integrations.v1.PendingItem.queued_at:type_name -> google.protobuf.Timestamp
	6,  // 3: wisdom.integrations.v1.PendingQueue.items:type_name -> wisdom.integrations.v1.PendingItem
	12, // 4: wisdom.integrations.v1.AnkiReviewEntry.reviewed_at:type_name -> google.protobuf.Timestamp
	9,  // 5: wisdom.integrations.v1.AnkiReviewBatch.reviews:type_name -> wisdom.integrations.v1.AnkiReviewEntry
	2,  // 6: wisdom.integrations.v1.Integrations.CreateNote:input_type -> wisdom.integrations.v1.NoteRequest
	3,  // 7: wisdom.integrations.v1.Integrations.CreateCard:input_type -> wisdom.integrations.v1.CardRequest
	5,  // 8: wisdom.integrations.v1.Integrations.GetPendingQueue:input_type -> wisdom.integrations.v1.QueueRequest
	5,  // 9: wisdom.integrations.v1.Integrations.RetryPendingSync:input_type -> wisdom.integrations.v1.QueueRequest
	10, // 10: wisdom.integrations.v1.Integrations.ProcessAnkiReviews:input_type -> wisdom.integrations.v1.AnkiReviewBatch
	4,  // 11: wisdom.integrations.v1.Integrations.CreateNote:output_type -> wisdom.integrations.v1.IntegrationResult
	4,  // 12: wisdom.integrations.v1.Integrations.CreateCard:output_type -> wisdom.integrations.v1.IntegrationResult
	7,  // 13: wisdom.integrations.v1.Integrations.GetPendingQueue:output_type -> wisdom.integrations.v1.PendingQueue
	8,  // 14: wisdom.integrations.v1.Integrations.RetryPendingSync:output_type -> wisdom.integrations.v1.RetryResult
	11, // 15: wisdom.integrations.v1.Integrations.ProcessAnkiReviews:output_type -> wisdom.integrations.v1.AnkiSyncResult
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_integrations_proto_init() }
func file_proto_integrations_proto_init() {
	if File_proto_integrations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_integrations_proto_rawDesc), len(file_proto_integrations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_integrations_proto_goTypes,
		DependencyIndexes: file_proto_integrations_proto_depIdxs,
		EnumInfos:         file_proto_integrations_proto_enumTypes,
		MessageInfos:      file_proto_integrations_proto_msgTypes,
	}.Build()
	File_proto_integrations_proto = out.File
	file_proto_integrations_proto_goTypes = nil
	file_proto_integrations_proto_depIdxs = nil
}
