// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/integrations.proto

package integrationsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Integrations_CreateNote_FullMethodName         = "/wisdom.integrations.v1.Integrations/CreateNote"
	Integrations_CreateCard_FullMethodName         = "/wisdom.integrations.v1.Integrations/CreateCard"
	Integrations_GetPendingQueue_FullMethodName    = "/wisdom.integrations.v1.Integrations/GetPendingQueue"
	Integrations_RetryPendingSync_FullMethodName   = "/wisdom.integrations.v1.Integrations/RetryPendingSync"
	Integrations_ProcessAnkiReviews_FullMethodName = "/wisdom.integrations.v1.Integrations/ProcessAnkiReviews"
)

// IntegrationsClient is the client API for Integrations service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Wisdom-Integrations: the single authoritative bridge between Expert Agents
// and external UI tools (Obsidian, Anki, Logseq).
// Rule: Expert Agents NEVER call MCP servers directly. All requests go through here.
type IntegrationsClient interface {
	// Create an Obsidian/Logseq Markdown note.
	CreateNote(ctx context.Context, in *NoteRequest, opts ...grpc.CallOption) (*IntegrationResult, error)
	// Create an Anki flashcard in a given deck.
	CreateCard(ctx context.Context, in *CardRequest, opts ...grpc.CallOption) (*IntegrationResult, error)
	// Get all items currently pending sync (MCP server was offline).
	GetPendingQueue(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*PendingQueue, error)
	// Retry all pending items in the queue.
	RetryPendingSync(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*RetryResult, error)
	// Receive an Anki review batch (called by the internal Anki polling job).
	ProcessAnkiReviews(ctx context.Context, in *AnkiReviewBatch, opts ...grpc.CallOption) (*AnkiSyncResult, error)
}

type integrationsClient struct {
	cc grpc.ClientConnInterface
}

func NewIntegrationsClient(cc grpc.ClientConnInterface) IntegrationsClient {
	return &integrationsClient{cc}
}

func (c *integrationsClient) CreateNote(ctx context.Context, in *NoteRequest, opts ...grpc.CallOption) (*IntegrationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntegrationResult)
	err := c.cc.Invoke(ctx, Integrations_CreateNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationsClient) CreateCard(ctx context.Context, in *CardRequest, opts ...grpc.CallOption) (*IntegrationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntegrationResult)
	err := c.cc.Invoke(ctx, Integrations_CreateCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationsClient) GetPendingQueue(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*PendingQueue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PendingQueue)
	err := c.cc.Invoke(ctx, Integrations_GetPendingQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationsClient) RetryPendingSync(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*RetryResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryResult)
	err := c.cc.Invoke(ctx, Integrations_RetryPendingSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationsClient) ProcessAnkiReviews(ctx context.Context, in *AnkiReviewBatch, opts ...grpc.CallOption) (*AnkiSyncResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnkiSyncResult)
	err := c.cc.Invoke(ctx, Integrations_ProcessAnkiReviews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrationsServer is the server API for Integrations service.
// All implementations must embed UnimplementedIntegrationsServer
// for forward compatibility.
//
// Wisdom-Integrations: the single authoritative bridge between Expert Agents
// and external UI tools (Obsidian, Anki, Logseq).
// Rule: Expert Agents NEVER call MCP servers directly. All requests go through here.
type IntegrationsServer interface {
	// Create an Obsidian/Logseq Markdown note.
	CreateNote(context.Context, *NoteRequest) (*IntegrationResult, error)
	// Create an Anki flashcard in a given deck.
	CreateCard(context.Context, *CardRequest) (*IntegrationResult, error)
	// Get all items currently pending sync (MCP server was offline).
	GetPendingQueue(context.Context, *QueueRequest) (*PendingQueue, error)
	// Retry all pending items in the queue.
	RetryPendingSync(context.Context, *QueueRequest) (*RetryResult, error)
	// Receive an Anki review batch (called by the internal Anki polling job).
	ProcessAnkiReviews(context.Context, *AnkiReviewBatch) (*AnkiSyncResult, error)
	mustEmbedUnimplementedIntegrationsServer()
}

// UnimplementedIntegrationsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntegrationsServer struct{}

func (UnimplementedIntegrationsServer) CreateNote(context.Context, *NoteRequest) (*IntegrationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNote not implemented")
}
func (UnimplementedIntegrationsServer) CreateCard(context.Context, *CardRequest) (*IntegrationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCard not implemented")
}
func (UnimplementedIntegrationsServer) GetPendingQueue(context.Context, *QueueRequest) (*PendingQueue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingQueue not implemented")
}
func (UnimplementedIntegrationsServer) RetryPendingSync(context.Context, *QueueRequest) (*RetryResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryPendingSync not implemented")
}
func (UnimplementedIntegrationsServer) ProcessAnkiReviews(context.Context, *AnkiReviewBatch) (*AnkiSyncResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessAnkiReviews not implemented")
}
func (UnimplementedIntegrationsServer) mustEmbedUnimplementedIntegrationsServer() {}
func (UnimplementedIntegrationsServer) testEmbeddedByValue()                      {}

// UnsafeIntegrationsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntegrationsServer will
// result in compilation errors.
type UnsafeIntegrationsServer interface {
	mustEmbedUnimplementedIntegrationsServer()
}

func RegisterIntegrationsServer(s grpc.ServiceRegistrar, srv IntegrationsServer) {
	// If the following call panics, it indicates UnimplementedIntegrationsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Integrations_ServiceDesc, srv)
}

func _Integrations_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationsServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integrations_CreateNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationsServer).CreateNote(ctx, req.(*NoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integrations_CreateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationsServer).CreateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integrations_CreateCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationsServer).CreateCard(ctx, req.(*CardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integrations_GetPendingQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationsServer).GetPendingQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integrations_GetPendingQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationsServer).GetPendingQueue(ctx, req.(*QueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integrations_RetryPendingSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationsServer).RetryPendingSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integrations_RetryPendingSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationsServer).RetryPendingSync(ctx, req.(*QueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integrations_ProcessAnkiReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnkiReviewBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationsServer).ProcessAnkiReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Integrations_ProcessAnkiReviews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationsServer).ProcessAnkiReviews(ctx, req.(*AnkiReviewBatch))
	}
	return interceptor(ctx, in, info, handler)
}

// Integrations_ServiceDesc is the grpc.ServiceDesc for Integrations service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Integrations_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wisdom.integrations.v1.Integrations",
	HandlerType: (*IntegrationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNote",
			Handler:    _Integrations_CreateNote_Handler,
		},
		{
			MethodName: "CreateCard",
			Handler:    _Integrations_CreateCard_Handler,
		},
		{
			MethodName: "GetPendingQueue",
			Handler:    _Integrations_GetPendingQueue_Handler,
		},
		{
			MethodName: "RetryPendingSync",
			Handler:    _Integrations_RetryPendingSync_Handler,
		},
		{
			MethodName: "ProcessAnkiReviews",
			Handler:    _Integrations_ProcessAnkiReviews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/integrations.proto",
}
