// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/researcher.proto

package researcherv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Researcher_Investigate_FullMethodName   = "/wisdom.researcher.v1.Researcher/Investigate"
	Researcher_SubscribeFeed_FullMethodName = "/wisdom.researcher.v1.Researcher/SubscribeFeed"
	Researcher_IngestBook_FullMethodName    = "/wisdom.researcher.v1.Researcher/IngestBook"
	Researcher_GetJobStatus_FullMethodName  = "/wisdom.researcher.v1.Researcher/GetJobStatus"
)

// ResearcherClient is the client API for Researcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Wisdom-Researcher: autonomous content gathering microservice.
// Publishes KNOWLEDGE.ingested events to GCP Pub/Sub on completion.
type ResearcherClient interface {
	// Trigger an investigation on a topic. Returns a stream of Markdown signals.
	Investigate(ctx context.Context, in *InvestigateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResearchSignal], error)
	// Add a URL or RSS feed to the autonomous crawler subscription list.
	SubscribeFeed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedAck, error)
	// Ingest a local PDF or book from a DDL source (Anna's Archive, local path).
	IngestBook(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*BookAck, error)
	// Get the status of a running research job.
	GetJobStatus(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatus, error)
}

type researcherClient struct {
	cc grpc.ClientConnInterface
}

func NewResearcherClient(cc grpc.ClientConnInterface) ResearcherClient {
	return &researcherClient{cc}
}

func (c *researcherClient) Investigate(ctx context.Context, in *InvestigateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ResearchSignal], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Researcher_ServiceDesc.Streams[0], Researcher_Investigate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InvestigateRequest, ResearchSignal]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Researcher_InvestigateClient = grpc.ServerStreamingClient[ResearchSignal]

func (c *researcherClient) SubscribeFeed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedAck)
	err := c.cc.Invoke(ctx, Researcher_SubscribeFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *researcherClient) IngestBook(ctx context.Context, in *BookRequest, opts ...grpc.CallOption) (*BookAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookAck)
	err := c.cc.Invoke(ctx, Researcher_IngestBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *researcherClient) GetJobStatus(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatus)
	err := c.cc.Invoke(ctx, Researcher_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResearcherServer is the server API for Researcher service.
// All implementations must embed UnimplementedResearcherServer
// for forward compatibility.
//
// Wisdom-Researcher: autonomous content gathering microservice.
// Publishes KNOWLEDGE.ingested events to GCP Pub/Sub on completion.
type ResearcherServer interface {
	// Trigger an investigation on a topic. Returns a stream of Markdown signals.
	Investigate(*InvestigateRequest, grpc.ServerStreamingServer[ResearchSignal]) error
	// Add a URL or RSS feed to the autonomous crawler subscription list.
	SubscribeFeed(context.Context, *FeedRequest) (*FeedAck, error)
	// Ingest a local PDF or book from a DDL source (Anna's Archive, local path).
	IngestBook(context.Context, *BookRequest) (*BookAck, error)
	// Get the status of a running research job.
	GetJobStatus(context.Context, *JobStatusRequest) (*JobStatus, error)
	mustEmbedUnimplementedResearcherServer()
}

// UnimplementedResearcherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResearcherServer struct{}

func (UnimplementedResearcherServer) Investigate(*InvestigateRequest, grpc.ServerStreamingServer[ResearchSignal]) error {
	return status.Error(codes.Unimplemented, "method Investigate not implemented")
}
func (UnimplementedResearcherServer) SubscribeFeed(context.Context, *FeedRequest) (*FeedAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SubscribeFeed not implemented")
}
func (UnimplementedResearcherServer) IngestBook(context.Context, *BookRequest) (*BookAck, error) {
	return nil, status.Error(codes.Unimplemented, "method IngestBook not implemented")
}
func (UnimplementedResearcherServer) GetJobStatus(context.Context, *JobStatusRequest) (*JobStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedResearcherServer) mustEmbedUnimplementedResearcherServer() {}
func (UnimplementedResearcherServer) testEmbeddedByValue()                    {}

// UnsafeResearcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResearcherServer will
// result in compilation errors.
type UnsafeResearcherServer interface {
	mustEmbedUnimplementedResearcherServer()
}

func RegisterResearcherServer(s grpc.ServiceRegistrar, srv ResearcherServer) {
	// If the following call panics, it indicates UnimplementedResearcherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Researcher_ServiceDesc, srv)
}

func _Researcher_Investigate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InvestigateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResearcherServer).Investigate(m, &grpc.GenericServerStream[InvestigateRequest, ResearchSignal]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Researcher_InvestigateServer = grpc.ServerStreamingServer[ResearchSignal]

func _Researcher_SubscribeFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResearcherServer).SubscribeFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Researcher_SubscribeFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResearcherServer).SubscribeFeed(ctx, req.(*FeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Researcher_IngestBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResearcherServer).IngestBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Researcher_IngestBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResearcherServer).IngestBook(ctx, req.(*BookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Researcher_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResearcherServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Researcher_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResearcherServer).GetJobStatus(ctx, req.(*JobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Researcher_ServiceDesc is the grpc.ServiceDesc for Researcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Researcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wisdom.researcher.v1.Researcher",
	HandlerType: (*ResearcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubscribeFeed",
			Handler:    _Researcher_SubscribeFeed_Handler,
		},
		{
			MethodName: "IngestBook",
			Handler:    _Researcher_IngestBook_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _Researcher_GetJobStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Investigate",
			Handler:       _Researcher_Investigate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/researcher.proto",
}
