// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/researcher.proto

package researcherv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvestigateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`   // e.g., "Caro-Kann Defense" or "React Server Components"
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"` // "chess", "technology", "finance", "language"
	Depth         int32                  `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`  // 1=surface, 3=deep (more sources)
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvestigateRequest) Reset() {
	*x = InvestigateRequest{}
	mi := &file_proto_researcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvestigateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestigateRequest) ProtoMessage() {}

func (x *InvestigateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_researcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestigateRequest.ProtoReflect.Descriptor instead.
func (*InvestigateRequest) Descriptor() ([]byte, []int) {
	return file_proto_researcher_proto_rawDescGZIP(), []int{0}
}

func (x *InvestigateRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *InvestigateRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *InvestigateRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *InvestigateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ResearchSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`                     // URL or file path
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                   // Raw Markdown/text chunk
	NodeType      string                 `protobuf:"bytes,4,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"` // "Fact", "Signal", "Concept"
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	ScrapedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=scraped_at,json=scrapedAt,proto3" json:"scraped_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResearchSignal) Reset() {
	*x = ResearchSignal{}
	mi := &file_proto_researcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResearchSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResearchSignal) ProtoMessage() {}

func (x *ResearchSignal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_researcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResearchSignal.ProtoReflect.Descriptor instead.
func (*ResearchSignal) Descriptor() ([]byte, []int) {
	return file_proto_researcher_proto_rawDescGZIP(), []int{1}
}

func (x *ResearchSignal) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ResearchSignal) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ResearchSignal) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ResearchSignal) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *ResearchSignal) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ResearchSignal) GetScrapedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScrapedAt
	}
	return nil
}

type FeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`       // RSS/Atom feed URL
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"` // Topic domain for classification
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedRequest) Reset() {
	*x = FeedRequest{}
	mi := &file_proto_researcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedRequest) ProtoMessage() {}

func (x *FeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_researcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedRequest.ProtoReflect.Descriptor instead.
func (*FeedRequest) Descriptor() ([]byte, []int) {
	return file_proto_researcher_proto_rawDescGZIP(), []int{2}
}

func (x *FeedRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FeedRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *FeedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FeedAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedId        string                 `protobuf:"bytes,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedAck) Reset() {
	*x = FeedAck{}
	mi := &file_proto_researcher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedAck) ProtoMessage() {}

func (x *FeedAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_researcher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedAck.ProtoReflect.Descriptor instead.
func (*FeedAck) Descriptor() ([]byte, []int) {
	return file_proto_researcher_proto_rawDescGZIP(), []int{3}
}

func (x *FeedAck) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

func (x *FeedAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceUri     string                 `protobuf:"bytes,1,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"` // Local path, GCS URI, or DDL URL
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookRequest) Reset() {
	*x = BookRequest{}
	mi := &file_proto_researcher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRequest) ProtoMessage() {}

func (x *BookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_researcher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRequest.ProtoReflect.Descriptor instead.
func (*BookRequest) Descriptor() ([]byte, []int) {
	return file_proto_researcher_proto_rawDescGZIP(), []int{4}
}

func (x *BookRequest) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *BookRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *BookRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BookAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Queued        bool                   `protobuf:"varint,2,opt,name=queued,proto3" json:"queued,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookAck) Reset() {
	*x = BookAck{}
	mi := &file_proto_researcher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookAck) ProtoMessage() {}

func (x *BookAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_researcher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookAck.ProtoReflect.Descriptor instead.
func (*BookAck) Descriptor() ([]byte, []int) {
	return file_proto_researcher_proto_rawDescGZIP(), []int{5}
}

func (x *BookAck) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *BookAck) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

type JobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusRequest) Reset() {
	*x = JobStatusRequest{}
	mi := &file_proto_researcher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusRequest) ProtoMessage() {}

func (x *JobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_researcher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusRequest.ProtoReflect.Descriptor instead.
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_researcher_proto_rawDescGZIP(), []int{6}
}

func (x *JobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "QUEUED", "CRAWLING", "PROCESSING", "DONE", "ERROR"
	ProgressPct   int32                  `protobuf:"varint,3,opt,name=progress_pct,json=progressPct,proto3" json:"progress_pct,omitempty"`
	EtaSeconds    int32                  `protobuf:"varint,4,opt,name=eta_seconds,json=etaSeconds,proto3" json:"eta_seconds,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_proto_researcher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_researcher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_proto_researcher_proto_rawDescGZIP(), []int{7}
}

func (x *JobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStatus) GetProgressPct() int32 {
	if x != nil {
		return x.ProgressPct
	}
	return 0
}

func (x *JobStatus) GetEtaSeconds() int32 {
	if x != nil {
		return x.EtaSeconds
	}
	return 0
}

func (x *JobStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *JobStatus) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

var File_proto_researcher_proto protoreflect.FileDescriptor

const file_proto_researcher_proto_rawDesc = "" +
	"\n" +
	"\x16proto/researcher.proto\x12\x14wisdom.researcher.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"q\n" +
	"\x12InvestigateRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x05R\x05depth\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"\xc5\x01\n" +
	"\x0eResearchSignal\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tnode_type\x18\x04 \x01(\tR\bnodeType\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x129\n" +
	"\n" +
	"scraped_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tscrapedAt\"P\n" +
	"\vFeedRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"<\n" +
	"\aFeedAck\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\tR\x06feedId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"]\n" +
	"\vBookRequest\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x01 \x01(\tR\tsourceUri\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"8\n" +
	"\aBookAck\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06queued\x18\x02 \x01(\bR\x06queued\")\n" +
	"\x10JobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x9b\x02\n" +
	"\tJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12!\n" +
	"\fprogress_pct\x18\x03 \x01(\x05R\vprogressPct\x12\x1f\n" +
	"\veta_seconds\x18\x04 \x01(\x05R\n" +
	"etaSeconds\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt2\xe9\x02\n" +
	"\n" +
	"Researcher\x12_\n" +
	"\vInvestigate\x12(.wisdom.researcher.v1.InvestigateRequest\x1a$.wisdom.researcher.v1.ResearchSignal0\x01\x12Q\n" +
	"\rSubscribeFeed\x12!.wisdom.researcher.v1.FeedRequest\x1a\x1d.wisdom.researcher.v1.FeedAck\x12N\n" +
	"\n" +
	"IngestBook\x12!.wisdom.researcher.v1.BookRequest\x1a\x1d.wisdom.researcher.v1.BookAck\x12W\n" +
	"\fGetJobStatus\x12&.wisdom.researcher.v1.JobStatusRequest\x1a\x1f.wisdom.researcher.v1.JobStatusB9Z7github.com/google/wisdom/pkg/researcher/v1;researcherv1b\x06proto3"

var (
	file_proto_researcher_proto_rawDescOnce sync.Once
	file_proto_researcher_proto_rawDescData []byte
)

func file_proto_researcher_proto_rawDescGZIP() []byte {
	file_proto_researcher_proto_rawDescOnce.Do(func() {
		file_proto_researcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_researcher_proto_rawDesc), len(file_proto_researcher_proto_rawDesc)))
	})
	return file_proto_researcher_proto_rawDescData
}

var file_proto_researcher_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_researcher_proto_goTypes = []any{
	(*InvestigateRequest)(nil),    // 0: wisdom.researcher.v1.InvestigateRequest
	(*ResearchSignal)(nil),        // 1: wisdom.researcher.v1.ResearchSignal
	(*FeedRequest)(nil),           // 2: wisdom.researcher.v1.FeedRequest
	(*FeedAck)(nil),               // 3: wisdom.researcher.v1.FeedAck
	(*BookRequest)(nil),           // 4: wisdom.researcher.v1.BookRequest
	(*BookAck)(nil),               // 5: wisdom.researcher.v1.BookAck
	(*JobStatusRequest)(nil),      // 6: wisdom.researcher.v1.JobStatusRequest
	(*JobStatus)(nil),             // 7: wisdom.researcher.v1.JobStatus
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_proto_researcher_proto_depIdxs = []int32{
	8, // 0: wisdom.researcher.v1.ResearchSignal.scraped_at:type_name -> google.protobuf.Timestamp
	8, // 1: wisdom.researcher.v1.JobStatus.started_at:type_name -> google.protobuf.Timestamp
	8, // 2: wisdom.researcher.v1.JobStatus.finished_at:type_name -> google.protobuf.Timestamp
	0, // 3: wisdom.researcher.v1.Researcher.Investigate:input_type -> wisdom.researcher.v1.InvestigateRequest
	2, // 4: wisdom.researcher.v1.Researcher.SubscribeFeed:input_type -> wisdom.researcher.v1.FeedRequest
	4, // 5: wisdom.researcher.v1.Researcher.IngestBook:input_type -> wisdom.researcher.v1.BookRequest
	6, // 6: wisdom.researcher.v1.Researcher.GetJobStatus:input_type -> wisdom.researcher.v1.JobStatusRequest
	1, // 7: wisdom.researcher.v1.Researcher.Investigate:output_type -> wisdom.researcher.v1.ResearchSignal
	3, // 8: wisdom.researcher.v1.Researcher.SubscribeFeed:output_type -> wisdom.researcher.v1.FeedAck
	5, // 9: wisdom.researcher.v1.Researcher.IngestBook:output_type -> wisdom.researcher.v1.BookAck
	7, // 10: wisdom.researcher.v1.Researcher.GetJobStatus:output_type -> wisdom.researcher.v1.JobStatus
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_researcher_proto_init() }
func file_proto_researcher_proto_init() {
	if File_proto_researcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_researcher_proto_rawDesc), len(file_proto_researcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_researcher_proto_goTypes,
		DependencyIndexes: file_proto_researcher_proto_depIdxs,
		MessageInfos:      file_proto_researcher_proto_msgTypes,
	}.Build()
	File_proto_researcher_proto = out.File
	file_proto_researcher_proto_goTypes = nil
	file_proto_researcher_proto_depIdxs = nil
}
