// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/entity.proto

package entityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityScope int32

const (
	EntityScope_PRIVATE EntityScope = 0 // Only visible to the owner user
	EntityScope_GLOBAL  EntityScope = 1 // Shared across all users
)

// Enum value maps for EntityScope.
var (
	EntityScope_name = map[int32]string{
		0: "PRIVATE",
		1: "GLOBAL",
	}
	EntityScope_value = map[string]int32{
		"PRIVATE": 0,
		"GLOBAL":  1,
	}
)

func (x EntityScope) Enum() *EntityScope {
	p := new(EntityScope)
	*p = x
	return p
}

func (x EntityScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityScope) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_entity_proto_enumTypes[0].Descriptor()
}

func (EntityScope) Type() protoreflect.EnumType {
	return &file_proto_entity_proto_enumTypes[0]
}

func (x EntityScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityScope.Descriptor instead.
func (EntityScope) EnumDescriptor() ([]byte, []int) {
	return file_proto_entity_proto_rawDescGZIP(), []int{0}
}

type EntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SymbolText    string                 `protobuf:"bytes,1,opt,name=symbol_text,json=symbolText,proto3" json:"symbol_text,omitempty"` // e.g., "@ElonMusk" or "#LLM"
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Scope         EntityScope            `protobuf:"varint,3,opt,name=scope,proto3,enum=wisdom.entity.v1.EntityScope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityRequest) Reset() {
	*x = EntityRequest{}
	mi := &file_proto_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityRequest) ProtoMessage() {}

func (x *EntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityRequest.ProtoReflect.Descriptor instead.
func (*EntityRequest) Descriptor() ([]byte, []int) {
	return file_proto_entity_proto_rawDescGZIP(), []int{0}
}

func (x *EntityRequest) GetSymbolText() string {
	if x != nil {
		return x.SymbolText
	}
	return ""
}

func (x *EntityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EntityRequest) GetScope() EntityScope {
	if x != nil {
		return x.Scope
	}
	return EntityScope_PRIVATE
}

type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // e.g., "profession"
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // e.g., "Engineer"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_proto_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_proto_entity_proto_rawDescGZIP(), []int{1}
}

func (x *Attribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Attribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EntityProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`                           // e.g., "@ElonMusk"
	EntityType    string                 `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"` // "PERSON", "ORGANIZATION", "TOPIC", "CONCEPT"
	CanonicalName string                 `protobuf:"bytes,4,opt,name=canonical_name,json=canonicalName,proto3" json:"canonical_name,omitempty"`
	Attributes    []*Attribute           `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Scope         EntityScope            `protobuf:"varint,6,opt,name=scope,proto3,enum=wisdom.entity.v1.EntityScope" json:"scope,omitempty"`
	// RESOLUTION_REQUIRED: set when the symbol is ambiguous (e.g., @Jesus = multiple users)
	RequiresResolution bool `protobuf:"varint,7,opt,name=requires_resolution,json=requiresResolution,proto3" json:"requires_resolution,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EntityProfile) Reset() {
	*x = EntityProfile{}
	mi := &file_proto_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityProfile) ProtoMessage() {}

func (x *EntityProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityProfile.ProtoReflect.Descriptor instead.
func (*EntityProfile) Descriptor() ([]byte, []int) {
	return file_proto_entity_proto_rawDescGZIP(), []int{2}
}

func (x *EntityProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityProfile) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *EntityProfile) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EntityProfile) GetCanonicalName() string {
	if x != nil {
		return x.CanonicalName
	}
	return ""
}

func (x *EntityProfile) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *EntityProfile) GetScope() EntityScope {
	if x != nil {
		return x.Scope
	}
	return EntityScope_PRIVATE
}

func (x *EntityProfile) GetRequiresResolution() bool {
	if x != nil {
		return x.RequiresResolution
	}
	return false
}

type ContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"` // Raw Markdown text to scan
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"` // "NOTE", "CHAT", "SIGNAL"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentRequest) Reset() {
	*x = ContentRequest{}
	mi := &file_proto_entity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentRequest) ProtoMessage() {}

func (x *ContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentRequest.ProtoReflect.Descriptor instead.
func (*ContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_entity_proto_rawDescGZIP(), []int{3}
}

func (x *ContentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ContentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ContentRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`                     // The matched symbol (@, #, [[]])
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // Resolved entity ID
	EntityType    string                 `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	StartPos      int32                  `protobuf:"varint,4,opt,name=start_pos,json=startPos,proto3" json:"start_pos,omitempty"` // Character offset in original content
	EndPos        int32                  `protobuf:"varint,5,opt,name=end_pos,json=endPos,proto3" json:"end_pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_proto_entity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_proto_entity_proto_rawDescGZIP(), []int{4}
}

func (x *Tag) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Tag) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Tag) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Tag) GetStartPos() int32 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *Tag) GetEndPos() int32 {
	if x != nil {
		return x.EndPos
	}
	return 0
}

type TaggedContent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OriginalContent string                 `protobuf:"bytes,1,opt,name=original_content,json=originalContent,proto3" json:"original_content,omitempty"`
	Tags            []*Tag                 `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaggedContent) Reset() {
	*x = TaggedContent{}
	mi := &file_proto_entity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaggedContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaggedContent) ProtoMessage() {}

func (x *TaggedContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaggedContent.ProtoReflect.Descriptor instead.
func (*TaggedContent) Descriptor() ([]byte, []int) {
	return file_proto_entity_proto_rawDescGZIP(), []int{5}
}

func (x *TaggedContent) GetOriginalContent() string {
	if x != nil {
		return x.OriginalContent
	}
	return ""
}

func (x *TaggedContent) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	EntityType    string                 `protobuf:"bytes,2,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	CanonicalName string                 `protobuf:"bytes,3,opt,name=canonical_name,json=canonicalName,proto3" json:"canonical_name,omitempty"`
	Attributes    []*Attribute           `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Scope         EntityScope            `protobuf:"varint,6,opt,name=scope,proto3,enum=wisdom.entity.v1.EntityScope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_entity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_entity_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RegisterRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *RegisterRequest) GetCanonicalName() string {
	if x != nil {
		return x.CanonicalName
	}
	return ""
}

func (x *RegisterRequest) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *RegisterRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterRequest) GetScope() EntityScope {
	if x != nil {
		return x.Scope
	}
	return EntityScope_PRIVATE
}

type RelationshipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromEntityId  string                 `protobuf:"bytes,1,opt,name=from_entity_id,json=fromEntityId,proto3" json:"from_entity_id,omitempty"`
	ToEntityId    string                 `protobuf:"bytes,2,opt,name=to_entity_id,json=toEntityId,proto3" json:"to_entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipRequest) Reset() {
	*x = RelationshipRequest{}
	mi := &file_proto_entity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipRequest) ProtoMessage() {}

func (x *RelationshipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipRequest.ProtoReflect.Descriptor instead.
func (*RelationshipRequest) Descriptor() ([]byte, []int) {
	return file_proto_entity_proto_rawDescGZIP(), []int{7}
}

func (x *RelationshipRequest) GetFromEntityId() string {
	if x != nil {
		return x.FromEntityId
	}
	return ""
}

func (x *RelationshipRequest) GetToEntityId() string {
	if x != nil {
		return x.ToEntityId
	}
	return ""
}

type Relationship struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromEntityId  string                 `protobuf:"bytes,1,opt,name=from_entity_id,json=fromEntityId,proto3" json:"from_entity_id,omitempty"`
	ToEntityId    string                 `protobuf:"bytes,2,opt,name=to_entity_id,json=toEntityId,proto3" json:"to_entity_id,omitempty"`
	RelationType  string                 `protobuf:"bytes,3,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"` // "WORKS_AT", "MASTERED_BY", "PART_OF", "CONTRADICTS"
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_proto_entity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_proto_entity_proto_rawDescGZIP(), []int{8}
}

func (x *Relationship) GetFromEntityId() string {
	if x != nil {
		return x.FromEntityId
	}
	return ""
}

func (x *Relationship) GetToEntityId() string {
	if x != nil {
		return x.ToEntityId
	}
	return ""
}

func (x *Relationship) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *Relationship) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type RelationshipList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relationships []*Relationship        `protobuf:"bytes,1,rep,name=relationships,proto3" json:"relationships,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationshipList) Reset() {
	*x = RelationshipList{}
	mi := &file_proto_entity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationshipList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationshipList) ProtoMessage() {}

func (x *RelationshipList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_entity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationshipList.ProtoReflect.Descriptor instead.
func (*RelationshipList) Descriptor() ([]byte, []int) {
	return file_proto_entity_proto_rawDescGZIP(), []int{9}
}

func (x *RelationshipList) GetRelationships() []*Relationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

var File_proto_entity_proto protoreflect.FileDescriptor

const file_proto_entity_proto_rawDesc = "" +
	"\n" +
	"\x12proto/entity.proto\x12\x10wisdom.entity.v1\"~\n" +
	"\rEntityRequest\x12\x1f\n" +
	"\vsymbol_text\x18\x01 \x01(\tR\n" +
	"symbolText\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x123\n" +
	"\x05scope\x18\x03 \x01(\x0e2\x1d.wisdom.entity.v1.EntityScopeR\x05scope\"3\n" +
	"\tAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xa2\x02\n" +
	"\rEntityProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1f\n" +
	"\ventity_type\x18\x03 \x01(\tR\n" +
	"entityType\x12%\n" +
	"\x0ecanonical_name\x18\x04 \x01(\tR\rcanonicalName\x12;\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2\x1b.wisdom.entity.v1.AttributeR\n" +
	"attributes\x123\n" +
	"\x05scope\x18\x06 \x01(\x0e2\x1d.wisdom.entity.v1.EntityScopeR\x05scope\x12/\n" +
	"\x13requires_resolution\x18\a \x01(\bR\x12requiresResolution\"]\n" +
	"\x0eContentRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\"\x91\x01\n" +
	"\x03Tag\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x03 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tstart_pos\x18\x04 \x01(\x05R\bstartPos\x12\x17\n" +
	"\aend_pos\x18\x05 \x01(\x05R\x06endPos\"e\n" +
	"\rTaggedContent\x12)\n" +
	"\x10original_content\x18\x01 \x01(\tR\x0foriginalContent\x12)\n" +
	"\x04tags\x18\x02 \x03(\v2\x15.wisdom.entity.v1.TagR\x04tags\"\xfc\x01\n" +
	"\x0fRegisterRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1f\n" +
	"\ventity_type\x18\x02 \x01(\tR\n" +
	"entityType\x12%\n" +
	"\x0ecanonical_name\x18\x03 \x01(\tR\rcanonicalName\x12;\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2\x1b.wisdom.entity.v1.AttributeR\n" +
	"attributes\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x123\n" +
	"\x05scope\x18\x06 \x01(\x0e2\x1d.wisdom.entity.v1.EntityScopeR\x05scope\"]\n" +
	"\x13RelationshipRequest\x12$\n" +
	"\x0efrom_entity_id\x18\x01 \x01(\tR\ffromEntityId\x12 \n" +
	"\fto_entity_id\x18\x02 \x01(\tR\n" +
	"toEntityId\"\x9b\x01\n" +
	"\fRelationship\x12$\n" +
	"\x0efrom_entity_id\x18\x01 \x01(\tR\ffromEntityId\x12 \n" +
	"\fto_entity_id\x18\x02 \x01(\tR\n" +
	"toEntityId\x12#\n" +
	"\rrelation_type\x18\x03 \x01(\tR\frelationType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\"X\n" +
	"\x10RelationshipList\x12D\n" +
	"\rrelationships\x18\x01 \x03(\v2\x1e.wisdom.entity.v1.RelationshipR\rrelationships*&\n" +
	"\vEntityScope\x12\v\n" +
	"\aPRIVATE\x10\x00\x12\n" +
	"\n" +
	"\x06GLOBAL\x10\x012\xea\x02\n" +
	"\x10EntityDictionary\x12Q\n" +
	"\rResolveEntity\x12\x1f.wisdom.entity.v1.EntityRequest\x1a\x1f.wisdom.entity.v1.EntityProfile\x12O\n" +
	"\n" +
	"TagContent\x12 .wisdom.entity.v1.ContentRequest\x1a\x1f.wisdom.entity.v1.TaggedContent\x12T\n" +
	"\x0eRegisterEntity\x12!.wisdom.entity.v1.RegisterRequest\x1a\x1f.wisdom.entity.v1.EntityProfile\x12\\\n" +
	"\x0fGetRelationship\x12%.wisdom.entity.v1.RelationshipRequest\x1a\".wisdom.entity.v1.RelationshipListB1Z/github.com/google/wisdom/pkg/entity/v1;entityv1b\x06proto3"

var (
	file_proto_entity_proto_rawDescOnce sync.Once
	file_proto_entity_proto_rawDescData []byte
)

func file_proto_entity_proto_rawDescGZIP() []byte {
	file_proto_entity_proto_rawDescOnce.Do(func() {
		file_proto_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_entity_proto_rawDesc), len(file_proto_entity_proto_rawDesc)))
	})
	return file_proto_entity_proto_rawDescData
}

var file_proto_entity_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_entity_proto_goTypes = []any{
	(EntityScope)(0),            // 0: wisdom.entity.v1.EntityScope
	(*EntityRequest)(nil),       // 1: wisdom.entity.v1.EntityRequest
	(*Attribute)(nil),           // 2: wisdom.entity.v1.Attribute
	(*EntityProfile)(nil),       // 3: wisdom.entity.v1.EntityProfile
	(*ContentRequest)(nil),      // 4: wisdom.entity.v1.ContentRequest
	(*Tag)(nil),                 // 5: wisdom.entity.v1.Tag
	(*TaggedContent)(nil),       // 6: wisdom.entity.v1.TaggedContent
	(*RegisterRequest)(nil),     // 7: wisdom.entity.v1.RegisterRequest
	(*RelationshipRequest)(nil), // 8: wisdom.entity.v1.RelationshipRequest
	(*Relationship)(nil),        // 9: wisdom.entity.v1.Relationship
	(*RelationshipList)(nil),    // 10: wisdom.entity.v1.RelationshipList
}
var file_proto_entity_proto_depIdxs = []int32{
	0,  // 0: wisdom.entity.v1.EntityRequest.scope:type_name -> wisdom.entity.v1.EntityScope
	2,  // 1: wisdom.entity.v1.EntityProfile.attributes:type_name -> wisdom.entity.v1.Attribute
	0,  // 2: wisdom.entity.v1.EntityProfile.scope:type_name -> wisdom.entity.v1.EntityScope
	5,  // 3: wisdom.entity.v1.TaggedContent.tags:type_name -> wisdom.entity.v1.Tag
	2,  // 4: wisdom.entity.v1.RegisterRequest.attributes:type_name -> wisdom.entity.v1.Attribute
	0,  // 5: wisdom.entity.v1.RegisterRequest.scope:type_name -> wisdom.entity.v1.EntityScope
	9,  // 6: wisdom.entity.v1.RelationshipList.relationships:type_name -> wisdom.entity.v1.Relationship
	1,  // 7: wisdom.entity.v1.EntityDictionary.ResolveEntity:input_type -> wisdom.entity.v1.EntityRequest
	4,  // 8: wisdom.entity.v1.EntityDictionary.TagContent:input_type -> wisdom.entity.v1.ContentRequest
	7,  // 9: wisdom.entity.v1.EntityDictionary.RegisterEntity:input_type -> wisdom.entity.v1.RegisterRequest
	8,  // 10: wisdom.entity.v1.EntityDictionary.GetRelationship:input_type -> wisdom.entity.v1.RelationshipRequest
	3,  // 11: wisdom.entity.v1.EntityDictionary.ResolveEntity:output_type -> wisdom.entity.v1.EntityProfile
	6,  // 12: wisdom.entity.v1.EntityDictionary.TagContent:output_type -> wisdom.entity.v1.TaggedContent
	3,  // 13: wisdom.entity.v1.EntityDictionary.RegisterEntity:output_type -> wisdom.entity.v1.EntityProfile
	10, // 14: wisdom.entity.v1.EntityDictionary.GetRelationship:output_type -> wisdom.entity.v1.RelationshipList
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_entity_proto_init() }
func file_proto_entity_proto_init() {
	if File_proto_entity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_entity_proto_rawDesc), len(file_proto_entity_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_entity_proto_goTypes,
		DependencyIndexes: file_proto_entity_proto_depIdxs,
		EnumInfos:         file_proto_entity_proto_enumTypes,
		MessageInfos:      file_proto_entity_proto_msgTypes,
	}.Build()
	File_proto_entity_proto = out.File
	file_proto_entity_proto_goTypes = nil
	file_proto_entity_proto_depIdxs = nil
}
