// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/entity.proto

package entityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EntityDictionary_ResolveEntity_FullMethodName   = "/wisdom.entity.v1.EntityDictionary/ResolveEntity"
	EntityDictionary_TagContent_FullMethodName      = "/wisdom.entity.v1.EntityDictionary/TagContent"
	EntityDictionary_RegisterEntity_FullMethodName  = "/wisdom.entity.v1.EntityDictionary/RegisterEntity"
	EntityDictionary_GetRelationship_FullMethodName = "/wisdom.entity.v1.EntityDictionary/GetRelationship"
)

// EntityDictionaryClient is the client API for EntityDictionary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Wisdom-Entity-Dictionary: ontology service for entity resolution and tagging.
// Identifies and contextualizes the "Who", "What", and "How" in the knowledge graph.
type EntityDictionaryClient interface {
	// Resolve a symbolic reference (@Person, #Topic) to a full entity profile.
	ResolveEntity(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*EntityProfile, error)
	// Scan a piece of content and tag all entities within it.
	TagContent(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*TaggedContent, error)
	// Register a new entity in the dictionary.
	RegisterEntity(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*EntityProfile, error)
	// Find relationships between two entities.
	GetRelationship(ctx context.Context, in *RelationshipRequest, opts ...grpc.CallOption) (*RelationshipList, error)
}

type entityDictionaryClient struct {
	cc grpc.ClientConnInterface
}

func NewEntityDictionaryClient(cc grpc.ClientConnInterface) EntityDictionaryClient {
	return &entityDictionaryClient{cc}
}

func (c *entityDictionaryClient) ResolveEntity(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*EntityProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityProfile)
	err := c.cc.Invoke(ctx, EntityDictionary_ResolveEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityDictionaryClient) TagContent(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*TaggedContent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaggedContent)
	err := c.cc.Invoke(ctx, EntityDictionary_TagContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityDictionaryClient) RegisterEntity(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*EntityProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntityProfile)
	err := c.cc.Invoke(ctx, EntityDictionary_RegisterEntity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entityDictionaryClient) GetRelationship(ctx context.Context, in *RelationshipRequest, opts ...grpc.CallOption) (*RelationshipList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelationshipList)
	err := c.cc.Invoke(ctx, EntityDictionary_GetRelationship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntityDictionaryServer is the server API for EntityDictionary service.
// All implementations must embed UnimplementedEntityDictionaryServer
// for forward compatibility.
//
// Wisdom-Entity-Dictionary: ontology service for entity resolution and tagging.
// Identifies and contextualizes the "Who", "What", and "How" in the knowledge graph.
type EntityDictionaryServer interface {
	// Resolve a symbolic reference (@Person, #Topic) to a full entity profile.
	ResolveEntity(context.Context, *EntityRequest) (*EntityProfile, error)
	// Scan a piece of content and tag all entities within it.
	TagContent(context.Context, *ContentRequest) (*TaggedContent, error)
	// Register a new entity in the dictionary.
	RegisterEntity(context.Context, *RegisterRequest) (*EntityProfile, error)
	// Find relationships between two entities.
	GetRelationship(context.Context, *RelationshipRequest) (*RelationshipList, error)
	mustEmbedUnimplementedEntityDictionaryServer()
}

// UnimplementedEntityDictionaryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntityDictionaryServer struct{}

func (UnimplementedEntityDictionaryServer) ResolveEntity(context.Context, *EntityRequest) (*EntityProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveEntity not implemented")
}
func (UnimplementedEntityDictionaryServer) TagContent(context.Context, *ContentRequest) (*TaggedContent, error) {
	return nil, status.Error(codes.Unimplemented, "method TagContent not implemented")
}
func (UnimplementedEntityDictionaryServer) RegisterEntity(context.Context, *RegisterRequest) (*EntityProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterEntity not implemented")
}
func (UnimplementedEntityDictionaryServer) GetRelationship(context.Context, *RelationshipRequest) (*RelationshipList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRelationship not implemented")
}
func (UnimplementedEntityDictionaryServer) mustEmbedUnimplementedEntityDictionaryServer() {}
func (UnimplementedEntityDictionaryServer) testEmbeddedByValue()                          {}

// UnsafeEntityDictionaryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntityDictionaryServer will
// result in compilation errors.
type UnsafeEntityDictionaryServer interface {
	mustEmbedUnimplementedEntityDictionaryServer()
}

func RegisterEntityDictionaryServer(s grpc.ServiceRegistrar, srv EntityDictionaryServer) {
	// If the following call panics, it indicates UnimplementedEntityDictionaryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EntityDictionary_ServiceDesc, srv)
}

func _EntityDictionary_ResolveEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityDictionaryServer).ResolveEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityDictionary_ResolveEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityDictionaryServer).ResolveEntity(ctx, req.(*EntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityDictionary_TagContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityDictionaryServer).TagContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityDictionary_TagContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityDictionaryServer).TagContent(ctx, req.(*ContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityDictionary_RegisterEntity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityDictionaryServer).RegisterEntity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityDictionary_RegisterEntity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityDictionaryServer).RegisterEntity(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntityDictionary_GetRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityDictionaryServer).GetRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EntityDictionary_GetRelationship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityDictionaryServer).GetRelationship(ctx, req.(*RelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EntityDictionary_ServiceDesc is the grpc.ServiceDesc for EntityDictionary service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntityDictionary_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wisdom.entity.v1.EntityDictionary",
	HandlerType: (*EntityDictionaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveEntity",
			Handler:    _EntityDictionary_ResolveEntity_Handler,
		},
		{
			MethodName: "TagContent",
			Handler:    _EntityDictionary_TagContent_Handler,
		},
		{
			MethodName: "RegisterEntity",
			Handler:    _EntityDictionary_RegisterEntity_Handler,
		},
		{
			MethodName: "GetRelationship",
			Handler:    _EntityDictionary_GetRelationship_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/entity.proto",
}
