FROM golang:1.26.3-bookworm AS builder

WORKDIR /app

# Copy go.mod and go.sum
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o thalamus-server ./cmd/thalamus/main.go

# Final minimal stage
FROM gcr.io/distroless/static-debian11

WORKDIR /

COPY --from=builder /app/thalamus-server /thalamus-server

# Expose the gRPC port
EXPOSE 50052

ENTRYPOINT ["/thalamus-server"]
