FROM golang:1.25-bullseye AS builder

WORKDIR /app

# Copy go.mod and go.sum
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code
COPY . .

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cerebellum-worker ./cmd/cerebellum/main.go

# Final minimal stage
FROM gcr.io/distroless/static-debian11

WORKDIR /

COPY --from=builder /app/cerebellum-worker /cerebellum-worker

ENTRYPOINT ["/cerebellum-worker"]
