FROM golang:1.25-bookworm AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o /integrations-server ./cmd/integrations/main.go

FROM gcr.io/distroless/static-debian12
COPY --from=builder /integrations-server /integrations-server
EXPOSE 50056
ENTRYPOINT ["/integrations-server"]
