FROM golang:1.25-bookworm AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o /entity-server ./cmd/entity/main.go

FROM gcr.io/distroless/static-debian12
COPY --from=builder /entity-server /entity-server
EXPOSE 50057
ENTRYPOINT ["/entity-server"]
